from __future__ import annotations

from pathlib import Path

ROOT = Path(__file__).resolve().parent
OUT = ROOT / "formulas" / "collections" / "Premium_Mass_4000_THB_Universal_Eighteen_2026-05-02.md"


FUNCTIONS = {
    "Bergamot FCF Sicilian": "polished bitter-citrus lift, richer than plain bergamot",
    "Cedrat FCF oil Sicilian": "bitter citron edge for clean expensive top-note cut",
    "Grapefruit FCF": "pithy dry citrus lift for mass-appeal freshness",
    "Blood Orange oil Sicilian": "juicy sweet-orange body without raw terpene harshness",
    "Red Mandarin EO": "warm mandarin sweetness for amber and gourmand openings",
    "Lime Distilled EO": "cold tart lime snap, cleaner than expressed lime",
    "Petitgrain EO": "green neroli-citrus bridge into floral or cologne heart",
    "Orange Peel EO": "simple orange-peel burst for familiar freshness",
    "D-Limonene": "short raw citrus volatility, used only as quick top lift",
    "Lemonile": "aldehydic lemon sparkle with better persistence than lemon oil",
    "Aldehyde C10": "fatty aldehydic sparkle at 1% trace",
    "Aldehyde C11": "clean soapy aldehydic lift at 1% trace",
    "Aldehyde C11 undecylenic": "metallic-green aldehydic projection at 1% trace",
    "Aldehyde C12 MNA": "orange-metallic aldehydic shimmer at 1% trace",
    "Hexyl Acetate": "pear-green fruit top from 10% working dilution",
    "Apritone": "apricot-citrus sparkle and long fruit lift from 10% stock",
    "Methyl Pamplemousse": "grapefruit-rhubarb tartness from 10% TEC stock",
    "Ethyl 2-Methylbutyrate": "juicy apple/pineapple trace impact",
    "Pink Pepper Base": "rosy pepper sparkle without heavy spice",
    "Black Pepper FTEC": "pepper top accent for masculine lift",
    "Cardamom EO": "green eucalyptol cardamom top, fresher than FTEC",
    "Terpinyl Acetate": "pine-citrus herbal acetate for fougere lift",
    "Ethyl Linalool": "woody-floral linalool lift with better tenacity than plain linalool",
    "Linalyl Acetate": "smooth citrus-lavender ester bridge for cologne heart",
    "Dihydromyrcenol": "fresh-laundry diffusion and blue-cologne lift",
    "Beta-Pinene": "pine-green terpene snap at top",
    "Juniper Berry EO": "gin-conifer aromatic freshness",
    "Rosemary EO (French Rosmarinus Officinalis leaf oil)": "herbal-camphoraceous aromatic lift",
    "Lavender EO": "soft aromatic fougere body",
    "Spike Lavender EO": "camphoraceous lavender bite for masculine definition",
    "Clary Sage EO": "ambery-herbal fougere texture",
    "Hedione": "jasmonate radiance amplifier and heart-volume expander",
    "Hedione HC": "high-cis jasmonate diffusion with less citrus bite",
    "Dihydrojasmone": "soft jasmine-petal realism",
    "Jasmine FO": "mass-prestige jasmine body at controlled cost",
    "Ylang Comoros Complete EO F3255": "creamy yellow-floral natural body",
    "Neroli EO": "natural orange-blossom freshness",
    "Oranger Crystals": "orange-blossom crystalline floral lift",
    "Hydroxycitronellal": "clean muguet body and floral diffusion",
    "Mayol": "transparent muguet-lily lift",
    "Lilyreal ND": "synthetic clean muguet volume",
    "Florol": "fresh dewy muguet-floral body",
    "Peonile": "pink peony body and mass-appeal floral polish",
    "Phenethyl Alcohol": "rose alcohol body and floral solvent warmth",
    "PEDMC": "soft rose-magnolia floral body",
    "Geraniol": "rosy-green floral bridge",
    "Citronellol": "clean rosy-citronella floral extension",
    "Benzyl Acetate": "jasmine-fruity floral lift",
    "Methyl Anthranilate": "orange-blossom grape/jasmine trace warmth",
    "Methyl Benzoate": "medicinal floral-fruit trace, kept low",
    "Farnesol": "creamy floral-linden naturalistic fixative and soft floral glow",
    "ACA": "jasmine-muguet waxy floral diffusant",
    "Freesia HDI": "green watery floral transparency",
    "Nympheal": "water-lily floral musk radiance",
    "Dimethyl Benzyl Carbinyl Acetate (DBCA)": "gardenia-magnolia ester for cosmetic white floral depth",
    "Helional": "watery cyclamen-muguet transparency",
    "Cyclamen Aldehyde": "metallic green floral lift",
    "Aurantiol": "orange-blossom honey Schiff-base body",
    "Paradisamide": "long-lasting tropical fruit modifier",
    "Raspberry Ketone": "red-fruit cottony sweetness",
    "Alpha Damascone": "metallic rose-plum lift from 10% stock",
    "Damascone Beta": "fruity rose impact from 10% stock",
    "Damascol": "soft rose-plum body from 10% stock",
    "Damascenone": "rose-fruit power trace from 1% stock",
    "Rose Oxide": "metallic rose/lychee trace",
    "Alpha Irone": "orris-root powder from 30% stock",
    "Alpha Ionone": "violet-iris floral body",
    "Beta Ionone": "woody violet depth",
    "Alpha Isomethyl Ionone": "woody iris-violet body",
    "Dihydro Beta Ionone": "woody violet drydown depth",
    "Ultralia": "ghost iris powder haze",
    "Irotyl": "suede-orris violet texture",
    "Orivone": "buttery warm orris base",
    "Orris F-TEC": "prebuilt iris foundation used as accent",
    "I-IRIS F-TEC": "prebuilt iris accord used as small bridge",
    "Iso E Super": "abstract cedar skin-cocoon and diffusion frame",
    "Cashmeran": "warm textile musk-wood texture",
    "Polysantol": "diffusive sandalwood persistence",
    "Javanol": "dry mineral sandalwood intimacy",
    "Ebanol": "creamy soft sandalwood texture",
    "Bacdanol": "round milky sandalwood body",
    "Sandalore": "fresh light sandalwood support",
    "Sandalwood FO": "mass-prestige warm sandalwood fill",
    "Cedramber": "cedar-amber bridge and base diffusion",
    "Amberwood F": "dry transparent amber-wood warmth",
    "Ambermax": "warm rounded amber body from 50% stock",
    "Amber Core": "amber accord support from 10% stock",
    "Azarbre": "smooth warm cedar-amber body",
    "Ambrox Super": "crystalline mineral amber from 30% stock",
    "Ambrofix": "smoother mineral amber from 30% stock",
    "Timberol": "dry architectural cedar structure",
    "Koavone": "warm cedarwood support",
    "Norlimbanol Dextro": "trace high-impact woody tenacity",
    "Cedarwood oil Virginia": "natural cedar pencil-shaving warmth",
    "Cedarwood EO": "natural cedarwood body",
    "Vetiver EO": "earthy dry vetiver anchor",
    "Vetival": "suede-vetiver dryness",
    "Vetikon": "clean modern vetiver support",
    "Patchouli EO": "natural patchouli earth and chypre body",
    "Clearwood": "clean chocolate-patchouli depth without dirt",
    "Nagarmortha Oil": "dry cypriol smoke/earth oud shadow",
    "Evernyl": "oakmoss replacement and chypre/fougere anchor",
    "Suederal": "soft suede-leather texture from 10% stock",
    "Isobutyl Quinoline": "dirty leather trace from 10% stock",
    "Costus Olifac": "skin-animal trace from 10% stock",
    "Birch Tar Rectified": "smoky leather trace, kept extremely low",
    "Guaiacol": "phenolic smoke trace from 10% stock",
    "Oud Fleuressence": "smooth mass-prestige oud body",
    "Tobacco FTEC": "mass tobacco body",
    "Tobacco Fleuressence": "richer honeyed tobacco accent",
    "Ethyl Safranate": "saffron-leather trace",
    "Cinnamyl alcohol 50% in DPG": "warm cinnamon-floral tobacco bridge from available diluted stock",
    "Cinnamaldehyde": "cinnamon-spice trace, kept below IFRA Cat 4 pressure points",
    "Vanillin": "vanilla sweetness from 10% stock",
    "Ethyl Vanillin": "high-impact vanilla sweetness",
    "Ethyl Maltol": "cotton-candy sweetness from 10% stock",
    "Coumarin": "tonka hay sweetness from 20% stock",
    "Tonka Bean FO": "mass tonka warmth",
    "Maple Lactone": "praline-maple gourmand body from 20% stock",
    "Benzoin Resinoid": "balsamic vanilla fixation from 50% stock",
    "Siam Benzoin": "softer balsamic vanilla fixation from 50% stock",
    "Benzoin Sumatra Resinoid": "darker balsamic trace from 10% stock",
    "Anisaldehyde": "almond-anise powder sweetness",
    "Heliotropal": "almond-heliotrope powder body",
    "Gamma Decalactone": "creamy peach/apricot lactone",
    "Gamma Undecalactone": "peach-skin lactone",
    "Delta Decalactone": "coconut-milk lactone",
    "Methyl Nonyl Ketone": "coconut-rue cream trace",
    "Allyl Amyl Glycolate": "green pineapple-laundry sparkle",
    "Blackcurrant FTEC": "cassis fruit hook for rose chypre without gourmand drift",
    "Calone": "watery marine trace from 1% stock",
    "Floralozone": "marine floral ozone from 10% stock",
    "Scentenal": "metallic green ozone from 1% stock",
    "Triplal": "ultra-fresh watery aldehydic trace",
    "Melonal": "honeydew aquatic fruit body",
    "Galaxolide": "clean musky projection and mass-market familiarity",
    "Habanolide": "warm skin macrocyclic musk",
    "Romandolide": "diffusive woody-clean projection musk",
    "Zenolide": "citrusy clean musk for fresh structures",
    "Macrolide": "transparent modern musk from 10% stock",
    "Ambrettolide": "naturalistic fruity skin musk from 10% stock",
    "Tonalide": "floral polycyclic musk from 10% stock",
    "Ethylene Brassylate": "lactonic long-tenacity musk",
    "Musk Ketone": "powdery talc musk from 10% working dilution",
    "Benzyl Salicylate": "heavy cosmetic salicylate cushion and fixation",
    "Hexyl Salicylate": "transparent green-floral salicylate film",
    "Benzyl Benzoate": "near-odorless balsamic fixative mass",
}


def row(layer: str, material: str, dilution: str, ul: float):
    return (layer, material, dilution, ul, FUNCTIONS.get(material, "specific accord support"))


FORMULAS = [
    {
        "name": "Silver Neroli Musk",
        "family": "Floral",
        "sub": "Neroli White Floral Musk",
        "gender": "M",
        "strength": "30 mL EDP @ 17%",
        "ref": "Prada L'Homme clean floral / Dior Homme Cologne cleanliness",
        "lock": "Floral family locked by neroli-muguet-Hedione heart; woods and musks are transparent supports only.",
        "diff": "DBCA + Nympheal add a modern water-lily/gardenia shimmer uncommon in male clean florals.",
        "rows": [
            row("TOP", "Bergamot FCF Sicilian", "neat", 220),
            row("", "Cedrat FCF oil Sicilian", "neat", 120),
            row("", "Petitgrain EO", "neat", 120),
            row("", "Aldehyde C11", "1 %", 35),
            row("", "Aldehyde C12 MNA", "1 %", 20),
            row("HEART", "Hedione", "neat", 550),
            row("", "Hedione HC", "neat", 160),
            row("", "Neroli EO", "neat", 80),
            row("", "Oranger Crystals", "neat", 70),
            row("", "Hydroxycitronellal", "neat", 140),
            row("", "Mayol", "neat", 80),
            row("", "Dimethyl Benzyl Carbinyl Acetate (DBCA)", "neat", 45),
            row("", "Nympheal", "neat", 60),
            row("", "Dihydrojasmone", "neat", 50),
            row("BASE", "Iso E Super", "neat", 360),
            row("", "Ambrox Super", "30 %", 260),
            row("", "Hexyl Salicylate", "neat", 180),
            row("", "Benzyl Salicylate", "neat", 160),
            row("", "Galaxolide", "100 %", 300),
            row("", "Romandolide", "neat", 160),
            row("", "Zenolide", "neat", 90),
            row("", "Macrolide", "10 %", 80),
            row("", "Ethylene Brassylate", "neat", 140),
            row("", "Cedarwood oil Virginia", "neat", 100),
            row("", "Cedramber", "neat", 70),
            row("", "Sandalore", "neat", 130),
            row("", "Amberwood F", "neat", 130),
            row("", "Cashmeran", "neat", 80),
        ],
    },
    {
        "name": "Ironed Shirt Iris",
        "family": "Floral",
        "sub": "Powdery Clean Iris",
        "gender": "M",
        "strength": "30 mL EDP @ 17%",
        "ref": "Dior Homme clean iris / Prada amber-iris cleanliness",
        "lock": "Powdery floral sub-family locked by ionone-irone-Florol-Mayol heart, not by woody amber.",
        "diff": "Ultralia + Ambrettolide makes the powder feel translucent and skin-warm rather than makeup-heavy.",
        "rows": [
            row("TOP", "Bergamot FCF Sicilian", "neat", 180),
            row("", "Grapefruit FCF", "neat", 120),
            row("", "Ethyl Linalool", "neat", 100),
            row("", "Aldehyde C11", "1 %", 40),
            row("", "Aldehyde C12 MNA", "1 %", 30),
            row("HEART", "Alpha Isomethyl Ionone", "neat", 260),
            row("", "Alpha Irone", "30 %", 220),
            row("", "Alpha Ionone", "neat", 60),
            row("", "Beta Ionone", "neat", 35),
            row("", "Ultralia", "neat", 30),
            row("", "Hedione", "neat", 450),
            row("", "Florol", "neat", 100),
            row("", "Mayol", "neat", 80),
            row("", "PEDMC", "neat", 60),
            row("", "Freesia HDI", "neat", 60),
            row("BASE", "Musk Ketone", "10 %", 250),
            row("", "Galaxolide", "100 %", 280),
            row("", "Romandolide", "neat", 160),
            row("", "Ambrox Super", "30 %", 220),
            row("", "Iso E Super", "neat", 350),
            row("", "Cashmeran", "neat", 110),
            row("", "Ethyl Linalool", "neat", 60),
            row("", "Hexyl Salicylate", "neat", 160),
            row("", "Benzyl Benzoate", "neat", 120),
            row("", "Sandalore", "neat", 100),
            row("", "Cedarwood oil Virginia", "neat", 80),
            row("", "Ethylene Brassylate", "neat", 180),
            row("", "Ambrettolide", "10 %", 100),
            row("", "Amberwood F", "neat", 120),
        ],
    },
    {
        "name": "Peony Gold Veil",
        "family": "Floral",
        "sub": "Fruity Floral",
        "gender": "F",
        "strength": "30 mL EDP @ 18%",
        "ref": "Lancôme Idôle / Miss Dior mass-prestige fruity floral",
        "lock": "Fruity floral locked by peony-Hedione-damascone heart; patchouli/amber kept only as fixative shadow.",
        "diff": "Paradisamide gives long tropical fruit lift while DBCA, Farnesol, and Ultralia add a polished floral shadow.",
        "rows": [
            row("TOP", "Blood Orange oil Sicilian", "neat", 180),
            row("", "Bergamot FCF Sicilian", "neat", 180),
            row("", "Hexyl Acetate", "10 %", 120),
            row("", "Apritone", "10 %", 100),
            row("", "Paradisamide", "10 %", 80),
            row("", "Aldehyde C11", "1 %", 35),
            row("HEART", "Hedione", "neat", 600),
            row("", "Hedione HC", "neat", 150),
            row("", "Peonile", "neat", 180),
            row("", "Phenethyl Alcohol", "neat", 160),
            row("", "Damascone Beta", "10 %", 60),
            row("", "Damascol", "10 %", 80),
            row("", "Damascenone", "1 %", 25),
            row("", "Nympheal", "neat", 70),
            row("", "Freesia HDI", "neat", 80),
            row("", "Dimethyl Benzyl Carbinyl Acetate (DBCA)", "neat", 60),
            row("BASE", "Galaxolide", "100 %", 350),
            row("", "Habanolide", "neat", 180),
            row("", "Ambrettolide", "10 %", 140),
            row("", "Romandolide", "neat", 100),
            row("", "Iso E Super", "neat", 280),
            row("", "Sandalore", "neat", 160),
            row("", "Benzyl Salicylate", "neat", 220),
            row("", "Hexyl Salicylate", "neat", 140),
            row("", "Ethylene Brassylate", "neat", 220),
            row("", "Ambrox Super", "30 %", 180),
            row("", "Vanillin", "10 %", 160),
            row("", "Cashmeran", "neat", 90),
            row("", "Clearwood", "neat", 60),
            row("", "Cedramber", "neat", 70),
            row("", "Macrolide", "10 %", 80),
            row("", "Ethyl Linalool", "neat", 85),
            row("", "Alpha Isomethyl Ionone", "neat", 70),
            row("", "Ultralia", "neat", 17),
            row("", "Dihydrojasmone", "neat", 50),
            row("", "Farnesol", "neat", 45),
        ],
    },
    {
        "name": "Bangkok Amber Blue",
        "family": "Oriental",
        "sub": "Fresh Amber Woods",
        "gender": "M",
        "strength": "30 mL EDP @ 18%",
        "ref": "YSL Y / Dylan Blue amber-fresh Thai mall style",
        "lock": "Fresh amber sub-family locked by amber-wood-musk base with citrus-aromatic top; not fougere because coumarin/lavender are restrained.",
        "diff": "Azarbre adds warm cedar-amber roundness so the Ambrox base does not read clinical.",
        "rows": [
            row("TOP", "Grapefruit FCF", "neat", 160),
            row("", "Bergamot FCF Sicilian", "neat", 180),
            row("", "Red Mandarin EO", "neat", 80),
            row("", "Pink Pepper Base", "neat", 80),
            row("", "Aldehyde C11", "1 %", 30),
            row("", "Dihydromyrcenol", "neat", 180),
            row("HEART", "Hedione", "neat", 450),
            row("", "Cardamom EO", "neat", 45),
            row("", "Lavender EO", "neat", 60),
            row("", "Clary Sage EO", "neat", 40),
            row("", "Ethyl Linalool", "neat", 110),
            row("BASE", "Ambrox Super", "30 %", 300),
            row("", "Ambrofix", "30 %", 180),
            row("", "Iso E Super", "neat", 450),
            row("", "Amberwood F", "neat", 180),
            row("", "Azarbre", "neat", 160),
            row("", "Ambermax", "50 %", 120),
            row("", "Habanolide", "neat", 160),
            row("", "Romandolide", "neat", 160),
            row("", "Galaxolide", "100 %", 280),
            row("", "Ethylene Brassylate", "neat", 180),
            row("", "Coumarin", "20 %", 120),
            row("", "Vanillin", "10 %", 120),
            row("", "Cedarwood oil Virginia", "neat", 140),
            row("", "Cashmeran", "neat", 120),
            row("", "Benzyl Benzoate", "neat", 120),
            row("", "Hexyl Salicylate", "neat", 100),
        ],
    },
    {
        "name": "Dark Tonka Tobacco",
        "family": "Oriental",
        "sub": "Tobacco Tonka Amber",
        "gender": "M",
        "strength": "30 mL EDP @ 20%",
        "ref": "Tobacco Vanille / Wanted by Night accessible amber",
        "lock": "Tobacco-tonka amber locked by tobacco fleuressence, coumarin, vanillin, benzoin, and warm amber materials.",
        "diff": "Ethyl Safranate + Suederal gives saffron-suede polish, while cedar/vetiver lift keeps the tobacco amber projecting.",
        "rows": [
            row("TOP", "Bergamot FCF Sicilian", "neat", 140),
            row("", "Red Mandarin EO", "neat", 100),
            row("", "Black Pepper FTEC", "neat", 70),
            row("", "Cardamom EO", "neat", 35),
            row("HEART", "Tobacco Fleuressence", "neat", 180),
            row("", "Tobacco FTEC", "neat", 120),
            row("", "Hedione", "neat", 300),
            row("", "Ethyl Safranate", "neat", 20),
            row("", "Cinnamaldehyde", "neat", 6),
            row("", "Damascol", "10 %", 40),
            row("", "Phenethyl Alcohol", "neat", 80),
            row("BASE", "Vanillin", "10 %", 300),
            row("", "Ethyl Vanillin", "neat", 70),
            row("", "Coumarin", "20 %", 220),
            row("", "Tonka Bean FO", "neat", 140),
            row("", "Benzoin Resinoid", "50 %", 220),
            row("", "Siam Benzoin", "50 %", 160),
            row("", "Ambermax", "50 %", 160),
            row("", "Amber Core", "10 %", 160),
            row("", "Iso E Super", "neat", 300),
            row("", "Ambrox Super", "30 %", 250),
            row("", "Galaxolide", "100 %", 260),
            row("", "Habanolide", "neat", 170),
            row("", "Ethylene Brassylate", "neat", 220),
            row("", "Clearwood", "neat", 120),
            row("", "Patchouli EO", "neat", 120),
            row("", "Cedarwood oil Virginia", "neat", 100),
            row("", "Suederal", "10 %", 60),
            row("", "Cedramber", "neat", 175),
            row("", "Amberwood F", "neat", 130),
            row("", "Cedarwood EO", "neat", 95),
            row("", "Vetiver EO", "neat", 65),
            row("", "Macrolide", "10 %", 95),
            row("", "Hedione", "neat", 130),
        ],
    },
    {
        "name": "Vanilla Silk Bloom",
        "family": "Oriental",
        "sub": "Vanilla Floral Amber",
        "gender": "F",
        "strength": "30 mL EDP @ 19%",
        "ref": "Black Opium / Mon Guerlain easy vanilla floral amber",
        "lock": "Vanilla floral amber locked by vanilla-benzoin-amber base and jasmine/ylang/orange-blossom heart.",
        "diff": "Ylang + Dihydrojasmone add a natural petal shadow to a very mass-appealing vanilla amber.",
        "rows": [
            row("TOP", "Bergamot FCF Sicilian", "neat", 160),
            row("", "Blood Orange oil Sicilian", "neat", 120),
            row("", "Pink Pepper Base", "neat", 60),
            row("", "Aldehyde C11", "1 %", 30),
            row("HEART", "Hedione", "neat", 520),
            row("", "Hedione HC", "neat", 130),
            row("", "Jasmine FO", "neat", 120),
            row("", "Ylang Comoros Complete EO F3255", "neat", 70),
            row("", "Oranger Crystals", "neat", 80),
            row("", "Dihydrojasmone", "neat", 60),
            row("", "Damascone Beta", "10 %", 50),
            row("", "Peonile", "neat", 100),
            row("BASE", "Vanillin", "10 %", 380),
            row("", "Ethyl Vanillin", "neat", 70),
            row("", "Benzoin Resinoid", "50 %", 200),
            row("", "Siam Benzoin", "50 %", 160),
            row("", "Ambermax", "50 %", 120),
            row("", "Amber Core", "10 %", 120),
            row("", "Sandalore", "neat", 160),
            row("", "Ebanol", "neat", 100),
            row("", "Iso E Super", "neat", 250),
            row("", "Galaxolide", "100 %", 280),
            row("", "Ethylene Brassylate", "neat", 220),
            row("", "Ambrettolide", "10 %", 130),
            row("", "Habanolide", "neat", 140),
            row("", "Macrolide", "10 %", 80),
            row("", "Ambrofix", "30 %", 60),
            row("", "Coumarin", "20 %", 160),
            row("", "Cashmeran", "neat", 100),
            row("", "Benzyl Salicylate", "neat", 180),
        ],
    },
    {
        "name": "Cobalt Cedar Air",
        "family": "Woody",
        "sub": "Aromatic Woody",
        "gender": "M",
        "strength": "30 mL EDP @ 18%",
        "ref": "Bleu de Chanel / Sauvage premium mass woods",
        "lock": "Aromatic woody locked by cedar-amber-Iso E spine; freshness is top support, not aquatic family drift.",
        "diff": "Norlimbanol trace gives a premium structural snap usually missing in safe blue woods.",
        "rows": [
            row("TOP", "Grapefruit FCF", "neat", 180),
            row("", "Bergamot FCF Sicilian", "neat", 150),
            row("", "Lemonile", "neat", 45),
            row("", "Aldehyde C11", "1 %", 35),
            row("", "Pink Pepper Base", "neat", 80),
            row("", "Dihydromyrcenol", "neat", 250),
            row("HEART", "Hedione", "neat", 420),
            row("", "Lavender EO", "neat", 80),
            row("", "Rosemary EO", "neat", 35),
            row("", "Geraniol", "neat", 50),
            row("", "Ethyl Linalool", "neat", 120),
            row("BASE", "Iso E Super", "neat", 550),
            row("", "Ambrox Super", "30 %", 300),
            row("", "Ambrofix", "30 %", 180),
            row("", "Cedramber", "neat", 220),
            row("", "Cedarwood oil Virginia", "neat", 180),
            row("", "Amberwood F", "neat", 180),
            row("", "Cashmeran", "neat", 120),
            row("", "Norlimbanol Dextro", "neat", 10),
            row("", "Galaxolide", "100 %", 300),
            row("", "Romandolide", "neat", 160),
            row("", "Habanolide", "neat", 160),
            row("", "Vetiver EO", "neat", 90),
            row("", "Patchouli EO", "neat", 70),
            row("", "Benzyl Benzoate", "neat", 120),
            row("", "Hexyl Salicylate", "neat", 100),
            row("", "Ethylene Brassylate", "neat", 160),
        ],
    },
    {
        "name": "Santal Sport Club",
        "family": "Woody",
        "sub": "Sandalwood Aromatic",
        "gender": "M",
        "strength": "30 mL EDP @ 18%",
        "ref": "Santal 33 made cleaner, Thai mall wearable",
        "lock": "Sandalwood aromatic locked by five-sandalwood stack; aromatics only open the structure.",
        "diff": "Sandalwood stack plus dry cedar/vetiver and a Norlimbanol trace gives premium wood grain without niche pickle harshness.",
        "rows": [
            row("TOP", "Bergamot FCF Sicilian", "neat", 150),
            row("", "Cedrat FCF oil Sicilian", "neat", 100),
            row("", "Juniper Berry EO", "neat", 60),
            row("", "Cardamom EO", "neat", 30),
            row("", "Terpinyl Acetate", "neat", 80),
            row("HEART", "Hedione", "neat", 350),
            row("", "Lavender EO", "neat", 60),
            row("", "Clary Sage EO", "neat", 40),
            row("BASE", "Polysantol", "neat", 220),
            row("", "Javanol", "neat", 90),
            row("", "Ebanol", "neat", 180),
            row("", "Bacdanol", "neat", 130),
            row("", "Sandalore", "neat", 180),
            row("", "Ethyl Linalool", "neat", 80),
            row("", "Dihydrojasmone", "neat", 50),
            row("", "Iso E Super", "neat", 420),
            row("", "Ambrox Super", "30 %", 220),
            row("", "Cedramber", "neat", 160),
            row("", "Amberwood F", "neat", 140),
            row("", "Galaxolide", "100 %", 260),
            row("", "Romandolide", "neat", 140),
            row("", "Habanolide", "neat", 120),
            row("", "Clearwood", "neat", 70),
            row("", "Cedarwood oil Virginia", "neat", 120),
            row("", "Ethylene Brassylate", "neat", 160),
            row("", "Hexyl Salicylate", "neat", 120),
            row("", "Benzyl Benzoate", "neat", 80),
            row("", "Cedarwood EO", "neat", 145),
            row("", "Vetiver EO", "neat", 145),
            row("", "Patchouli EO", "neat", 80),
            row("", "Amberwood F", "neat", 130),
            row("", "Norlimbanol Dextro", "neat", 6),
            row("", "Macrolide", "10 %", 95),
            row("", "Alpha Isomethyl Ionone", "neat", 80),
            row("", "Ethyl Linalool", "neat", 95),
        ],
    },
    {
        "name": "Cashmere Peach Woods",
        "family": "Woody",
        "sub": "Soft Creamy Woody",
        "gender": "F",
        "strength": "30 mL EDP @ 18%",
        "ref": "Burberry Her / Cashmere Mist woody-musky sweetness",
        "lock": "Soft creamy woody locked by Cashmeran, sandalwood, Iso E, and musks; peach is only the soft top hook.",
        "diff": "Suederal gives textile skin, while ylang/benzoin/farnesol add a creamy natural glow under the cashmere woods.",
        "rows": [
            row("TOP", "Bergamot FCF Sicilian", "neat", 140),
            row("", "Blood Orange oil Sicilian", "neat", 100),
            row("", "Hexyl Acetate", "10 %", 80),
            row("", "Apritone", "10 %", 60),
            row("", "Aldehyde C11", "1 %", 25),
            row("HEART", "Hedione", "neat", 450),
            row("", "Peonile", "neat", 120),
            row("", "Damascol", "10 %", 60),
            row("", "Alpha Isomethyl Ionone", "neat", 120),
            row("", "Nympheal", "neat", 50),
            row("", "PEDMC", "neat", 60),
            row("BASE", "Cashmeran", "neat", 180),
            row("", "Iso E Super", "neat", 360),
            row("", "Sandalore", "neat", 180),
            row("", "Ebanol", "neat", 120),
            row("", "Ambrox Super", "30 %", 200),
            row("", "Galaxolide", "100 %", 320),
            row("", "Ethylene Brassylate", "neat", 240),
            row("", "Habanolide", "neat", 160),
            row("", "Ambrettolide", "10 %", 100),
            row("", "Benzyl Salicylate", "neat", 180),
            row("", "Hexyl Salicylate", "neat", 120),
            row("", "Vanillin", "10 %", 140),
            row("", "Amberwood F", "neat", 120),
            row("", "Suederal", "10 %", 50),
            row("", "Ultralia", "neat", 15),
            row("", "Macrolide", "10 %", 80),
            row("", "Polysantol", "neat", 60),
            row("", "Ylang Comoros Complete EO F3255", "neat", 60),
            row("", "Benzoin Resinoid", "50 %", 130),
            row("", "Cedarwood EO", "neat", 115),
            row("", "Vetiver EO", "neat", 65),
            row("", "Ethyl Linalool", "neat", 130),
            row("", "Farnesol", "neat", 65),
            row("", "Macrolide", "10 %", 95),
            row("", "Gamma Decalactone", "neat", 35),
            row("", "Sandalore", "neat", 100),
        ],
    },
    {
        "name": "Green Patchouli Cologne",
        "family": "Chypre",
        "sub": "Citrus Patchouli Chypre",
        "gender": "M",
        "strength": "30 mL EDP @ 17%",
        "ref": "Terre d'Hermes / modern citrus patchouli office chypre",
        "lock": "Chypre locked by citrus top, patchouli/Clearwood/vetiver base with trace Evernyl; no gourmand drift.",
        "diff": "Clearwood modernizes the patchouli while keeping the citrus chypre skeleton readable.",
        "rows": [
            row("TOP", "Bergamot FCF Sicilian", "neat", 220),
            row("", "Grapefruit FCF", "neat", 120),
            row("", "Petitgrain EO", "neat", 100),
            row("", "Aldehyde C11", "1 %", 35),
            row("", "Pink Pepper Base", "neat", 60),
            row("HEART", "Hedione", "neat", 380),
            row("", "Geraniol", "neat", 70),
            row("", "Phenethyl Alcohol", "neat", 80),
            row("", "Damascone Beta", "10 %", 40),
            row("", "Lavender EO", "neat", 50),
            row("", "Clary Sage EO", "neat", 35),
            row("", "Ethyl Linalool", "neat", 100),
            row("BASE", "Patchouli EO", "neat", 220),
            row("", "Clearwood", "neat", 193),
            row("", "Evernyl", "neat", 14),
            row("", "Vetiver EO", "neat", 162),
            row("", "Iso E Super", "neat", 340),
            row("", "Ambrox Super", "30 %", 220),
            row("", "Cedramber", "neat", 131),
            row("", "Benzyl Salicylate", "neat", 160),
            row("", "Hexyl Salicylate", "neat", 140),
            row("", "Galaxolide", "100 %", 240),
            row("", "Romandolide", "neat", 150),
            row("", "Habanolide", "neat", 120),
            row("", "Cedarwood oil Virginia", "neat", 120),
            row("", "Coumarin", "20 %", 80),
        ],
    },
    {
        "name": "Suede Moss Night",
        "family": "Chypre",
        "sub": "Leather Patchouli Chypre",
        "gender": "M",
        "strength": "30 mL EDP @ 18%",
        "ref": "Tom Ford leather-patchouli made safer and more wearable",
        "lock": "Leather chypre locked by patchouli, Clearwood, vetiver, Suederal, trace Evernyl, and trace IBQ.",
        "diff": "IBQ and Suederal create leather texture while avoiding birch-tar overload.",
        "rows": [
            row("TOP", "Bergamot FCF Sicilian", "neat", 180),
            row("", "Grapefruit FCF", "neat", 90),
            row("", "Black Pepper FTEC", "neat", 50),
            row("HEART", "Hedione", "neat", 330),
            row("", "Rose Oxide", "1 %", 40),
            row("", "Phenethyl Alcohol", "neat", 70),
            row("", "Geraniol", "neat", 50),
            row("", "Damascol", "10 %", 40),
            row("", "Ethyl Safranate", "neat", 15),
            row("BASE", "Patchouli EO", "neat", 267),
            row("", "Clearwood", "neat", 187),
            row("", "Evernyl", "neat", 12),
            row("", "Suederal", "10 %", 100),
            row("", "Isobutyl Quinoline", "10 %", 30),
            row("", "Vetiver EO", "neat", 134),
            row("", "Ambrox Super", "30 %", 220),
            row("", "Iso E Super", "neat", 320),
            row("", "Cedramber", "neat", 160),
            row("", "Amberwood F", "neat", 120),
            row("", "Galaxolide", "100 %", 220),
            row("", "Habanolide", "neat", 130),
            row("", "Ethylene Brassylate", "neat", 160),
            row("", "Benzoin Resinoid", "50 %", 100),
            row("", "Benzyl Salicylate", "neat", 150),
            row("", "Hexyl Salicylate", "neat", 100),
        ],
    },
    {
        "name": "Rose Cassis Chypre",
        "family": "Chypre",
        "sub": "Fruity Rose Chypre",
        "gender": "F",
        "strength": "30 mL EDP @ 18%",
        "ref": "Armani Si / Coco Mademoiselle rose-cassis chypre",
        "lock": "Fruity rose chypre locked by cassis/rose over patchouli-Clearwood-vetiver with trace Evernyl.",
        "diff": "Damascol softens the cassis rose while trace Evernyl and dry woods keep it chypre, not fruity floral.",
        "rows": [
            row("TOP", "Bergamot FCF Sicilian", "neat", 180),
            row("", "Blood Orange oil Sicilian", "neat", 120),
            row("", "Blackcurrant FTEC", "neat", 120),
            row("", "Methyl Pamplemousse", "10 %", 60),
            row("", "Aldehyde C11", "1 %", 30),
            row("HEART", "Hedione", "neat", 480),
            row("", "Phenethyl Alcohol", "neat", 180),
            row("", "Peonile", "neat", 100),
            row("", "Damascone Beta", "10 %", 60),
            row("", "Damascol", "10 %", 70),
            row("", "Rose Oxide", "1 %", 40),
            row("", "Nympheal", "neat", 60),
            row("", "Freesia HDI", "neat", 60),
            row("", "Ethyl Linalool", "neat", 60),
            row("BASE", "Patchouli EO", "neat", 198),
            row("", "Clearwood", "neat", 142),
            row("", "Evernyl", "neat", 14),
            row("", "Vetiver EO", "neat", 11),
            row("", "Cedramber", "neat", 5),
            row("", "Iso E Super", "neat", 280),
            row("", "Ambrox Super", "30 %", 200),
            row("", "Galaxolide", "100 %", 280),
            row("", "Habanolide", "neat", 160),
            row("", "Ambrettolide", "10 %", 100),
            row("", "Benzyl Salicylate", "neat", 220),
            row("", "Hexyl Salicylate", "neat", 120),
            row("", "Vanillin", "10 %", 100),
            row("", "Ethylene Brassylate", "neat", 180),
            row("", "Cedarwood oil Virginia", "neat", 80),
        ],
    },
    {
        "name": "Aromatic Barbershop Blue",
        "family": "Fougere",
        "sub": "Aromatic Fougere",
        "gender": "M",
        "strength": "30 mL EDP @ 17%",
        "ref": "modern barbershop / Legend / Platinum Egoiste mass appeal",
        "lock": "Fougere locked by citrus-aromatic-lavender-coumarin-vetiver with trace Evernyl structure.",
        "diff": "Juniper and Rosemary add Thai hot-weather aromatic lift without marine drift.",
        "rows": [
            row("TOP", "Bergamot FCF Sicilian", "neat", 180),
            row("", "Grapefruit FCF", "neat", 120),
            row("", "Dihydromyrcenol", "neat", 260),
            row("", "Aldehyde C11", "1 %", 40),
            row("", "Juniper Berry EO", "neat", 60),
            row("", "Terpinyl Acetate", "neat", 80),
            row("HEART", "Lavender EO", "neat", 200),
            row("", "Spike Lavender EO", "neat", 70),
            row("", "Clary Sage EO", "neat", 70),
            row("", "Rosemary EO", "neat", 50),
            row("", "Hedione", "neat", 350),
            row("", "Geraniol", "neat", 80),
            row("BASE", "Coumarin", "20 %", 280),
            row("", "Tonka Bean FO", "neat", 120),
            row("", "Evernyl", "neat", 15),
            row("", "Vetiver EO", "neat", 143),
            row("", "Patchouli EO", "neat", 97),
            row("", "Iso E Super", "neat", 330),
            row("", "Ambrox Super", "30 %", 250),
            row("", "Cedramber", "neat", 165),
            row("", "Galaxolide", "100 %", 260),
            row("", "Habanolide", "neat", 140),
            row("", "Romandolide", "neat", 140),
            row("", "Ethylene Brassylate", "neat", 160),
            row("", "Cedarwood oil Virginia", "neat", 100),
            row("", "Amberwood F", "neat", 100),
        ],
    },
    {
        "name": "Mintless Tonka Club",
        "family": "Fougere",
        "sub": "Sweet Fougere",
        "gender": "M",
        "strength": "30 mL EDP @ 18%",
        "ref": "Le Male / Eros style without toothpaste mint",
        "lock": "Sweet fougere locked by lavender-coumarin-tonka base; vanilla supports but does not become oriental.",
        "diff": "Cardamom EO gives modern green-spice lift instead of the usual mint overdose.",
        "rows": [
            row("TOP", "Bergamot FCF Sicilian", "neat", 160),
            row("", "Red Mandarin EO", "neat", 100),
            row("", "Cardamom EO", "neat", 35),
            row("", "Pink Pepper Base", "neat", 60),
            row("", "Dihydromyrcenol", "neat", 180),
            row("HEART", "Lavender EO", "neat", 180),
            row("", "Spike Lavender EO", "neat", 60),
            row("", "Hedione", "neat", 320),
            row("", "Geraniol", "neat", 70),
            row("", "Heliotropal", "neat", 60),
            row("", "Anisaldehyde", "neat", 35),
            row("BASE", "Coumarin", "20 %", 320),
            row("", "Vanillin", "10 %", 240),
            row("", "Ethyl Vanillin", "neat", 45),
            row("", "Tonka Bean FO", "neat", 160),
            row("", "Benzoin Resinoid", "50 %", 120),
            row("", "Amber Core", "10 %", 140),
            row("", "Iso E Super", "neat", 300),
            row("", "Ambrox Super", "30 %", 220),
            row("", "Galaxolide", "100 %", 260),
            row("", "Ethylene Brassylate", "neat", 200),
            row("", "Habanolide", "neat", 150),
            row("", "Cashmeran", "neat", 100),
            row("", "Evernyl", "neat", 14),
            row("", "Vetiver EO", "neat", 98),
            row("", "Patchouli EO", "neat", 12),
            row("", "Cedramber", "neat", 11),
        ],
    },
    {
        "name": "Lavender Skin Cream",
        "family": "Fougere",
        "sub": "Lavender Vanilla Fougere",
        "gender": "F",
        "strength": "30 mL EDP @ 17%",
        "ref": "Mon Guerlain / Libre lavender-vanilla mass appeal",
        "lock": "Feminine fougere locked by lavender, coumarin, vanilla, and moss/wood trace; not pure amber because lavender remains central.",
        "diff": "Musk Ketone and Heliotropal add powder-cream texture around the lavender.",
        "rows": [
            row("TOP", "Bergamot FCF Sicilian", "neat", 150),
            row("", "Blood Orange oil Sicilian", "neat", 80),
            row("", "Aldehyde C11", "1 %", 30),
            row("HEART", "Lavender EO", "neat", 180),
            row("", "Hedione", "neat", 380),
            row("", "Hedione HC", "neat", 100),
            row("", "Florol", "neat", 80),
            row("", "Mayol", "neat", 70),
            row("", "Peonile", "neat", 80),
            row("", "Heliotropal", "neat", 50),
            row("BASE", "Coumarin", "20 %", 260),
            row("", "Vanillin", "10 %", 260),
            row("", "Siam Benzoin", "50 %", 120),
            row("", "Ebanol", "neat", 100),
            row("", "Sandalore", "neat", 150),
            row("", "Iso E Super", "neat", 250),
            row("", "Ambrox Super", "30 %", 200),
            row("", "Galaxolide", "100 %", 260),
            row("", "Ethylene Brassylate", "neat", 220),
            row("", "Ambrettolide", "10 %", 100),
            row("", "Musk Ketone", "10 %", 140),
            row("", "Benzyl Salicylate", "neat", 160),
            row("", "Hexyl Salicylate", "neat", 100),
            row("", "Cashmeran", "neat", 80),
            row("", "Nympheal", "neat", 40),
        ],
    },
    {
        "name": "Andaman Blue EDP",
        "family": "Fresh",
        "sub": "Aquatic Aromatic",
        "gender": "M",
        "strength": "30 mL EDP @ 17%",
        "ref": "Acqua di Gio Profumo / Bvlgari Aqva premium mass",
        "lock": "Fresh aquatic locked by Calone/Floralozone/Scentenal/DHM top-heart and mineral amber base.",
        "diff": "Scentenal gives mineral green-metallic texture, avoiding generic melon aquatic.",
        "rows": [
            row("TOP", "Bergamot FCF Sicilian", "neat", 170),
            row("", "Grapefruit FCF", "neat", 150),
            row("", "Lime Distilled EO", "neat", 100),
            row("", "Dihydromyrcenol", "neat", 300),
            row("", "Aldehyde C11", "1 %", 35),
            row("HEART", "Calone", "1 %", 90),
            row("", "Floralozone", "10 %", 90),
            row("", "Scentenal", "1 %", 30),
            row("", "Hedione", "neat", 380),
            row("", "Geraniol", "neat", 50),
            row("", "Rosemary EO", "neat", 30),
            row("", "Lavender EO", "neat", 60),
            row("BASE", "Ambrox Super", "30 %", 300),
            row("", "Ambrofix", "30 %", 180),
            row("", "Iso E Super", "neat", 360),
            row("", "Amberwood F", "neat", 150),
            row("", "Galaxolide", "100 %", 300),
            row("", "Zenolide", "neat", 120),
            row("", "Romandolide", "neat", 130),
            row("", "Habanolide", "neat", 100),
            row("", "Cedarwood oil Virginia", "neat", 100),
            row("", "Vetiver EO", "neat", 80),
            row("", "Hexyl Salicylate", "neat", 100),
            row("", "Ethylene Brassylate", "neat", 120),
        ],
    },
    {
        "name": "Citrus Tailored Musk",
        "family": "Fresh",
        "sub": "Citrus Cologne Intense",
        "gender": "M",
        "strength": "30 mL EDP @ 16%",
        "ref": "Acqua di Parma / Atelier Cologne premium citrus",
        "lock": "Fresh citrus cologne locked by heavy citrus-petitgrain-neroli top; woods/musks only extend.",
        "diff": "Zenolide plus Ambrox stretches citrus without turning it into blue amber.",
        "rows": [
            row("TOP", "Cedrat FCF oil Sicilian", "neat", 220),
            row("", "Bergamot FCF Sicilian", "neat", 200),
            row("", "Grapefruit FCF", "neat", 160),
            row("", "Blood Orange oil Sicilian", "neat", 100),
            row("", "Petitgrain EO", "neat", 100),
            row("", "Aldehyde C10", "1 %", 40),
            row("", "Aldehyde C11", "1 %", 35),
            row("HEART", "Neroli EO", "neat", 60),
            row("", "Hedione", "neat", 380),
            row("", "Ethyl Linalool", "neat", 160),
            row("", "Linalyl Acetate", "neat", 120),
            row("", "Rosemary EO", "neat", 25),
            row("", "Geraniol", "neat", 50),
            row("BASE", "Ambrox Super", "30 %", 240),
            row("", "Sandalore", "neat", 120),
            row("", "Iso E Super", "neat", 260),
            row("", "Cedarwood oil Virginia", "neat", 90),
            row("", "Galaxolide", "100 %", 220),
            row("", "Zenolide", "neat", 120),
            row("", "Romandolide", "neat", 120),
            row("", "Ethylene Brassylate", "neat", 140),
            row("", "Hexyl Salicylate", "neat", 120),
            row("", "Benzyl Benzoate", "neat", 100),
            row("", "Cashmeran", "neat", 60),
        ],
    },
    {
        "name": "Clean Pear Air",
        "family": "Fresh",
        "sub": "Fresh Fruity Floral",
        "gender": "F",
        "strength": "30 mL EDP @ 17%",
        "ref": "Chance Eau Tendre / Daisy clean fruity fresh",
        "lock": "Fresh fruity floral locked by pear/citrus top, airy floral heart, clean musk base; sweetness kept below gourmand threshold.",
        "diff": "Nympheal adds water-lily transparency so the pear floral stays fresh, not shampoo-flat.",
        "rows": [
            row("TOP", "Bergamot FCF Sicilian", "neat", 160),
            row("", "Blood Orange oil Sicilian", "neat", 120),
            row("", "Hexyl Acetate", "10 %", 100),
            row("", "Apritone", "10 %", 80),
            row("", "Aldehyde C11", "1 %", 30),
            row("", "Aldehyde C12 MNA", "1 %", 20),
            row("HEART", "Hedione", "neat", 520),
            row("", "Peonile", "neat", 120),
            row("", "Nympheal", "neat", 80),
            row("", "Florol", "neat", 80),
            row("", "Freesia HDI", "neat", 70),
            row("", "Damascol", "10 %", 50),
            row("", "PEDMC", "neat", 60),
            row("", "Helional", "neat", 60),
            row("BASE", "Galaxolide", "100 %", 320),
            row("", "Zenolide", "neat", 120),
            row("", "Habanolide", "neat", 140),
            row("", "Ethylene Brassylate", "neat", 180),
            row("", "Ambrox Super", "30 %", 180),
            row("", "Iso E Super", "neat", 260),
            row("", "Hexyl Salicylate", "neat", 140),
            row("", "Benzyl Benzoate", "neat", 120),
            row("", "Sandalore", "neat", 100),
            row("", "Ambrettolide", "10 %", 80),
            row("", "Cashmeran", "neat", 70),
            row("", "Cedramber", "neat", 70),
        ],
    },
]


def target_ul(formula):
    pct_text = formula["strength"].split("@", 1)[1].split("%", 1)[0].strip()
    return 30000 * float(pct_text) / 100


def apply_strength_targets():
    for formula in FORMULAS:
        if formula.get("_strength_targeted"):
            continue
        current = total_ul(formula)
        target = target_ul(formula)
        if current <= 0 or abs(target - current) <= 1:
            formula["_strength_targeted"] = True
            continue
        factor = target / current
        scaled_rows = []
        running = 0.0
        largest_idx = 0
        largest_ul = 0.0
        for idx, (layer, material, dilution, ul, function) in enumerate(formula["rows"]):
            scaled_ul = round(ul * factor, 1)
            if scaled_ul > largest_ul:
                largest_idx = idx
                largest_ul = scaled_ul
            running += scaled_ul
            scaled_rows.append((layer, material, dilution, scaled_ul, function))

        remainder = round(target - running, 1)
        if abs(remainder) >= 0.1:
            layer, material, dilution, ul, function = scaled_rows[largest_idx]
            scaled_rows[largest_idx] = (layer, material, dilution, round(ul + remainder, 1), function)

        formula["rows"] = scaled_rows
        formula["_strength_targeted"] = True


def total_ul(formula):
    return sum(item[3] for item in formula["rows"])


def pct(formula):
    return total_ul(formula) / 30000 * 100


def build():
    apply_strength_targets()
    lines = []
    lines.append("# PREMIUM MASS 4000+ THB UNIVERSAL EIGHTEEN - 6 Families x 3")
    lines.append("")
    lines.append("**Date:** 2026-05-02")
    lines.append("**Format:** 18 x 30 mL EDP concepts for the Thai 4,000+ THB / 100 mL designer-mass tier.")
    lines.append("**Brief:** each main family gets **2 masculine + 1 feminine** formulas. Each formula is optimized as a mass-appeal smell-good build with a small differentiator, while staying locked to its stated family and sub-family.")
    lines.append("**Inventory basis:** current `inventory.txt` as of 2026-05-02. Depleted Exaltolide and depleted Bergamot FCF are not used; Bergamot FCF Sicilian is used where bergamot is required.")
    lines.append("**Guardrails used:** vapor/ODT logic, top-heart-base trajectory, musk/amber/wood differentiation, skin substantivity, and avoiding receptor flooding by not letting one workhorse material carry the whole formula.")
    lines.append("")
    lines.append("## Collection Map")
    lines.append("")
    lines.append("| # | Name | Family | Sub-family | Gender | Format / Strength | Reference |")
    lines.append("|--:|---|---|---|---|---|---|")
    for i, f in enumerate(FORMULAS, 1):
        lines.append(f"| {i} | {f['name']} | {f['family']} | {f['sub']} | {f['gender']} | {f['strength']} | {f['ref']} |")
    lines.append("")
    lines.append("**Gender split:** per family = 2 masculine + 1 feminine. Total = 12 M + 6 F.")
    lines.append("")
    current_family = None
    family_num = 0
    for i, f in enumerate(FORMULAS, 1):
        if f["family"] != current_family:
            family_num += 1
            current_family = f["family"]
            lines.append("---")
            lines.append("")
            lines.append(f"# FAMILY {family_num} - {current_family.upper()}")
            lines.append("")
        total = total_ul(f)
        lines.append(f"## {i}. {f['name']} - {f['sub']} ({'Masculine' if f['gender'] == 'M' else 'Feminine'})")
        lines.append("")
        lines.append(f"**Family/sub-family lock:** {f['lock']}")
        lines.append(f"**Differentiator:** {f['diff']}")
        lines.append(f"**Concentrate:** {total:,.0f} uL = {pct(f):.1f}% of a 30 mL bottle.")
        lines.append("")
        lines.append("| Layer | # | Material | Dilution | uL | Function |")
        lines.append("|---|--:|---|---|---:|---|")
        n = 1
        for layer, material, dilution, ul, function in f["rows"]:
            layer_cell = layer
            lines.append(f"| {layer_cell} | {n} | {material} | {dilution} | {ul:g} | {function} |")
            n += 1
        lines.append(f"| **Total** | | | | **{total:,.0f}** | concentrate total |")
        lines.append("")
    OUT.write_text("\n".join(lines), encoding="utf-8")
    print(OUT.relative_to(ROOT))


if __name__ == "__main__":
    build()
