"""Scoring, the optimizer and recommendations use the release gate's VP.

The gate (``engine/pipeline/formula_state.py``) takes the 25 C reference VP
from the YAML data spine, then the ingredient-intelligence profile. The
optimizer's knowledge-graph records (``material_properties.json``, the
generated ingredient catalog, an optional SQLite DB) are regenerated by hand
and can carry stale VPs, so the scoring path must resolve VP the gate's way.
"""

from __future__ import annotations

import math

import pytest

from engine.inventory_parser import parse_current_inventory
from engine.material_resolver import resolve_material
from engine.optimizer.models import (
    FormulaVector,
    _gamma_from_logp,
    _get_logp,
    _lookup_material,
)


def _gate_vp(name: str) -> float | None:
    """The gate's precedence, read straight from the resolver's two sources."""
    resolved = resolve_material(name)
    reg_vp = getattr(resolved.registry_material, "vp_25c_pa", None)
    if reg_vp is not None:
        return float(reg_vp)
    profile_vp = getattr(resolved.profile, "vp", None)
    return float(profile_vp) if profile_vp is not None else None


def _owned_material_names() -> list[str]:
    names = {record.name for record in parse_current_inventory(include_solvents=False)}
    return sorted(names)


def _close(a: float, b: float) -> bool:
    return math.isclose(a, b, rel_tol=1e-9, abs_tol=0.0)


def test_owned_materials_have_gate_vp_inputs():
    names = _owned_material_names()
    assert len(names) > 50
    assert sum(1 for n in names if _gate_vp(n) is not None) > 50


def test_scoring_record_vp_equals_gate_vp_for_every_owned_material():
    disagreements = []
    for name in _owned_material_names():
        gate = _gate_vp(name)
        mat = _lookup_material(name)
        if gate is None or mat is None:
            continue
        scoring = mat.get("vp")
        if scoring is None or not _close(float(scoring), gate):
            disagreements.append(f"{name}: scoring={scoring} gate={gate}")
    assert not disagreements, "scoring VP differs from gate VP:\n" + "\n".join(disagreements)


def test_formula_vector_vp_equals_gate_vp_for_every_owned_material():
    disagreements = []
    for name in _owned_material_names():
        gate = _gate_vp(name)
        if gate is None:
            continue
        mat = _lookup_material(name)
        expected = gate * _gamma_from_logp(_get_logp(name, mat))
        scoring = FormulaVector(ingredients={name: 100.0}).avg_property("vp")
        if scoring is None or not _close(scoring, expected):
            disagreements.append(f"{name}: scoring={scoring} gate*gamma={expected}")
    assert not disagreements, "FormulaVector VP differs from gate VP:\n" + "\n".join(disagreements)


def test_hidden_fixative_recommendations_use_gate_vp():
    from engine.formula_recommendations import find_hidden_fixatives

    disagreements = [
        f"{row['name']}: recommendation={row['vp']} gate={_gate_vp(row['name'])}"
        for row in find_hidden_fixatives()
        if _gate_vp(row["name"]) is not None and not _close(row["vp"], _gate_vp(row["name"]))
    ]
    assert not disagreements, "\n".join(disagreements)


@pytest.mark.parametrize(
    ("name", "gate_vp"),
    [
        # YAML-only corrections that never reached material_properties.json.
        ("Lemon FCF oil Sicilian", 210.0),
        ("Benzyl Benzoate", 0.02986),
    ],
)
def test_known_yaml_corrections_reach_scoring(name, gate_vp):
    if _gate_vp(name) is None or not _close(_gate_vp(name), gate_vp):
        pytest.skip(f"data spine VP for {name} changed; agreement tests still cover it")
    mat = _lookup_material(name)
    assert mat is not None
    assert _close(float(mat["vp"]), gate_vp)
