# Pepper Current Parfum V1 — Controlled Blinded Validation Plan

**Plan ID:** PCP-V1-PPS-BV-20260829  
**Formula under test:** `PEPPER_CURRENT_PARFUM_V1_PINK_PEPPER_SPORT_30mL_22pct_THEORY.md`  
**Status:** THEORY PROTOCOL ONLY / NOT TESTED / NO COMPOUNDING AUTHORIZED  
**Primary question:** can exact owned Pink Pepper remain the first recognizable object while a genuinely athletic current transforms into a dense cedar-sandalwood Parfum interior?  
**Secondary question:** do the 35 rows create nonredundant spatial and temporal architecture, or does a controlled 28-row compression perform as well or better?

This plan does not authorize procurement, stock preparation, weighing, pipetting, skin application, wear testing, or release. It becomes executable only after separate physical authorization, bottle/lot/basis reconciliation, safety review, and a batch ledger. All sensory, luxury, similarity, depth, sport, performance, and hedonic outcomes remain **NOT TESTED**.

## 1. Evidence Ceiling and Trial Logic

- Official Chanel and Prada pages establish only broad structural axes. They do not disclose formulas and do not prove that this design resembles any reference.
- The user's unblinded rejection of the preceding direction is valid evidence to abandon that direction for this user, but it does not isolate a causal material or validate this replacement.
- The owned PerfumersWorld Pink Pepper Essential Oil `7SC00941` is a proprietary compound supplied as a nominal 10% DEP stock. Exact lot, bottle concentration basis, one-material physics, composite OAV, and material-specific safety are **HOLD**.
- Modeled ppm/OAV/headspace/temporal output is diagnostic only. A missing-physics zero for Pink Pepper is invalid as a sensory conclusion.
- Every stage is sequential. A later architecture or liking result cannot rescue failure of the literal lead-note gate.
- `Benzyl Benzoate` and `DEP` are volume compensators, not assumed odorless or behaviorally neutral. Every compensator change is recorded and, where decisive, checked in a separate matrix comparison.
- No arm may be called “better,” “sportier,” “deeper,” “luxurious,” “similar,” or “complete” until its coded physical samples have been compared under the defined ballot.

## 2. Preconditions Before Any Physical Trial

All items below are hard gates:

1. Re-read `AGENTS.md`, `inventory.txt`, `.github/copilot-instructions.md`, the studio method, the DHP2025 structural protocol, this plan, and the exact formula immediately before the batch.
2. Record SHA-256 for every authority and formula used.
3. Photograph and transcribe the Pink Pepper bottle label. Record supplier, SKU, lot, received date, nominal dilution, carrier, appearance, and storage history. Any conflict remains **HOLD**; do not silently rebase.
4. Resolve or explicitly retain HOLD for Ambrofix 30% w/v carrier, Amber Xtreme 10% w/w-to-volume mapping, Pink Pepper exact 10% basis, and natural-mixture safety/composite-OAV applicability.
5. Complete formula-specific IFRA/allergen and safe-handling review before any skin exposure. Blotter work does not waive handling safety.
6. Use only current physical inventory. Do not procure or substitute an absent material.
7. Preserve the **10 µL minimum direct raw-stock aliquot**. If a scaled trial would make any direct aliquot smaller, prepare a documented, labeled, carrier-matched working stock only after separate authorization; otherwise increase batch scale.
8. Use calibrated volumetric or gravimetric equipment appropriate to the reconciled stock basis. Record actual delivered mass/volume and deviations.
9. Prepare every decisive arm independently at least twice; do not split one master and call the splits independent preparations.
10. Use opaque randomized three-character codes generated by a person or process unavailable to the evaluator until lock.

## 3. Fixed Evaluation Conditions

Unless a later authorized protocol specifies otherwise:

- **Primary substrate:** identical unscented blotters from one lot.
- **Application:** constant deposited mass or reconciled volume per blotter, logged for every arm.
- **Environment:** one room, stable temperature/humidity, no ambient fragrance, evaluator fragrance-free.
- **Windows:** 0, 5, 30, and 120 minutes; 6 hours; 24 hours.
- **Replicates:** two independently made sample blocks, evaluated on separate sessions.
- **Order:** independently randomized within every time block; reverse or re-randomize order in replicate two.
- **Rest:** minimum five minutes between samples and longer when adaptation or fatigue is reported. No coffee-bean “reset.”
- **First pass:** free description before any prompted attributes.
- **Lock:** codes and choices are frozen before unblinding.
- **Skin:** prohibited until formula-specific safety review and separate authorization.

## 4. Core Ballot

Record raw language first, then the structured fields.

| Endpoint | Scale / record | Primary success requirement |
|---|---|---|
| first named object | verbatim free description | Pink Pepper or integrated rosy-effervescent woody pepper is first at 0-30 min |
| Pink Pepper recognition | 0-10 | at least 7 at 0-5 min and at least 5 at 30 min in the selected arm |
| athletic motion | 0-10 | at least 7 at 0-30 min; directional/moving rather than merely fresh |
| sport classification | forced choice plus confidence | sport/athletic chosen over shower gel, formal woody, aquatic, gourmand, or generic blue |
| warm Parfum depth | 0-10 | rises from 30 min without suppressing Pink Pepper recurrence |
| transition continuity | 0-10 | cold current becomes warm current without a hollow or abrupt seam |
| front / middle / rear separation | 0-10 each | three distinct planes reported without disjointedness |
| recurrence | yes/no plus description | pepper-linked identity is recalled at 2-6 h, not only wood/musk |
| comfort / fatigue | 0-10 plus reason | no dominant metallic, amberwood, lavender, ozone, or musk fatigue |
| liking / re-smell pull | 0-10 | descriptive only until replicated; never replaces identity gates |
| takeover checklist | yes/no per listed failure | no lavender soap, aquatic melon, literal rose/powder, ambrox wall, sweetness, or donor-signature takeover |
| similarity impression | free description only | recorded but not used as proof of formula similarity or reference reconstruction |

### Hard vetoes

Reject an arm regardless of liking if any of these repeats across both preparations:

- Dihydromyrcenol, citrus, lavender, generic blue freshness, or dry ambrox/wood is named before Pink Pepper.
- Pink Pepper becomes literal rose, lychee/plum, cosmetic powder, or hot Black Pepper.
- The fragrance is called static, formal-only, heavy, or non-sport at 0-30 minutes.
- Calone-like melon/sea spray, loud muguet, detergent, or shower gel becomes the identity.
- The 30-minute-to-6-hour perfume collapses into anonymous Iso E/ambrox/musk.
- Saffron leather, smoky oak, incense, pineapple/cassis/birch, vanilla/tonka dessert, or a recognizable donor signature appears.

## 5. Stage 0 — Literal Lead Recognition and Vehicle Control

**Question:** does the exact Pink Pepper stock create a recognizable subject, or is the background doing the identity work?

Use the exact 6,600 µL formula as arm `PP+`. For arm `PP0`, replace the full 2,000 µL Pink Pepper 10% DEP stock with 2,000 µL verified matching DEP. All other raw doses remain unchanged.

| Arm | Pink Pepper 10% DEP | Matching DEP add-back | Total concentrate | Interpretation |
|---|---:|---:|---:|---|
| PP+ | 2,000 µL | 0 µL | 6,600 µL | exact candidate |
| PP0 | 0 µL | 2,000 µL | 6,600 µL | no-lead vehicle control |

**Pass to Stage 1 only if:** `PP+` is correctly distinguishable from `PP0`; Pink Pepper is freely named or described in `PP+`; sport motion remains present; and no takeover veto fires. A mere preference for `PP+` is insufficient.

## 6. Stage 1 — Pink Pepper Leadership Dose Ladder

**Question:** what raw-stock level gives clear leadership without turning floral, fruity, hot, carrier-heavy, or static?

Create one 4,600 µL common background by retaining all formula materials except the 2,000 µL Pink Pepper stock. The common background retains the formula's full 110 µL Benzyl Benzoate. Add one 2,000 µL module:

| Arm | Pink Pepper 10% DEP | Matching DEP | Module total | Formula total | Nominal parent equivalent |
|---|---:|---:|---:|---:|---:|
| P12 | 1,200 µL | 800 µL | 2,000 µL | 6,600 µL | 120 µL |
| P16 | 1,600 µL | 400 µL | 2,000 µL | 6,600 µL | 160 µL |
| P20 | 2,000 µL | 0 µL | 2,000 µL | 6,600 µL | 200 µL |

This is raw-volume matched and uses the declared Pink Pepper carrier. Because parent active replaces a small amount of carrier as dose rises, exact carrier mass cannot be claimed without exact stock-basis and density data; that residual remains **HOLD**.

**Selection rule:** choose the lowest dose that wins Pink Pepper recognition and recurrence while preserving athletic motion, comfort, and a non-floral/non-fruity identity. Do not select by liking score alone.

### Stage 1B — Matrix Compensation Check

`P20` is the exact theory formula and requires no added DEP. If `P12` or `P16` is selected, compare its DEP-compensated ladder arm with an equal-volume Benzyl-Benzoate-compensated arm: keep the same Pink Pepper dose, remove the added DEP, and add the same raw volume of Benzyl Benzoate. For example, `P16-DEP` has 110 µL total Benzyl Benzoate plus 400 µL added DEP, while `P16-BB` has 510 µL total Benzyl Benzoate and no added DEP. If they differ materially, matrix choice is a design variable and must not be attributed to Pink Pepper dose.

## 7. Stage 2 — Sport-Motion Threshold: Dihydromyrcenol

**Question:** is 320 µL the minimum motion dose that reads as athletic while staying below the Pink Pepper subject?

Use a 6,200 µL common background made by removing the formula's 320 µL Dihydromyrcenol and 80 µL of Benzyl Benzoate; the background retains 30 µL Benzyl Benzoate. Add one 400 µL module:

| Arm | Dihydromyrcenol | Benzyl Benzoate add-back | Module total | Formula total |
|---|---:|---:|---:|---:|
| D24 | 240 µL | 160 µL | 400 µL | 6,600 µL |
| D32 | 320 µL | 80 µL | 400 µL | 6,600 µL |
| D40 | 400 µL | 0 µL | 400 µL | 6,600 µL |

**Selection rule:** choose the lowest level that gives unambiguous athletic direction in both preparations while Pink Pepper remains the first named object. Reject any level that becomes shower gel, laundry, metallic-lime cleaner, or generic blue.

## 8. Stage 3 — Citrus Shape, Not Citrus Leadership

**Question:** does the 70:50 grapefruit/lemon edge sharpen Pink Pepper and sport motion, or compete with the subject?

The exact citrus module is 120 µL. Keep its 7:5 ratio and use Benzyl Benzoate as the declared non-neutral compensator:

| Arm | Grapefruit FCF | Lemon FCF | Benzyl Benzoate add-back | Formula total |
|---|---:|---:|---:|---:|
| C0 | 0 µL | 0 µL | 120 µL | 6,600 µL |
| C50 | 35 µL | 25 µL | 60 µL | 6,600 µL |
| C100 | 70 µL | 50 µL | 0 µL | 6,600 µL |

**Selection rule:** citrus must increase directional opening and Pink Pepper clarity, not become the first object. A brighter arm that loses 30-minute identity fails.

## 9. Stage 4 — Architectural 2 x 2: Mineral Motion and Warm Parfum Interior

**Question:** do opposed mineral motion and warm interior jointly create depth and pressure/release, or are either/both decorative?

Modules:

- `M` mineral-motion module, 100 µL: Aldehyde C10 1% 20 + Scentenal 1% 10 + Helional 30 + Cyclamen Aldehyde 20 + Floralozone 10% 20.
- `W` warm-interior module, 280 µL: Alpha Isomethyl Ionone 30 + Ebanol 150 + Amberwood F 100.

Make a 6,110 µL common background by removing `M`, `W`, and all 110 µL of Benzyl Benzoate. Add one 490 µL module:

| Arm | Mineral module M | Warm module W | Benzyl Benzoate add-back | Module total | Formula total |
|---|---:|---:|---:|---:|---:|
| 00 | 0 µL | 0 µL | 490 µL | 490 µL | 6,600 µL |
| M0 | 100 µL | 0 µL | 390 µL | 490 µL | 6,600 µL |
| 0W | 0 µL | 280 µL | 210 µL | 490 µL | 6,600 µL |
| MW | 100 µL | 280 µL | 110 µL | 490 µL | 6,600 µL |

Read the interaction, not just the main effects:

- `M0 - 00`: mineral motion contribution without warm depth.
- `0W - 00`: warm interior contribution without mineral motion.
- `MW - M0`: whether warm depth improves a moving chassis.
- `MW - 0W`: whether mineral motion prevents static heaviness.
- `MW - M0 - 0W + 00`: whether the opposed textures interact rather than merely add.

`MW` survives only if it preserves Pink Pepper leadership, produces clearer front/middle/rear separation and a smoother cold-to-warm transition, and does not increase aquatic, cosmetic, or amberwood takeover. This stage directly decides whether the perfume has architectural “arms”: a forward mineral arm and a rear warm-wood arm held by the Pink Pepper current.

## 10. Stage 5 — Complete 35 Rows Versus Controlled 28-Row Compression

**Question:** do the seven smallest finishing gestures improve identity-bearing architecture enough to justify their presence?

The 28-row arm removes exactly 180 µL:

| Removed row | Raw amount | Claimed function being challenged |
|---|---:|---|
| Scentenal 1% | 10 µL | charged-air pin |
| Rose Oxide 1% | 10 µL | Pink Pepper metallic-rosy lens |
| Terpinyl Acetate | 20 µL | citrus-aromatic stitch |
| Floralozone 10% | 20 µL | lateral air aperture |
| Dihydrojasmone | 30 µL | dry moving-fabric gesture |
| Patchouli EO | 40 µL | natural dark shadow |
| Vetival | 50 µL | polished root finish |
| **Total removed** | **180 µL** |  |

Replace the 180 µL with Benzyl Benzoate, raising that row from 110 to 290 µL. Compare exact 35-row and compressed 28-row arms at constant 6,600 µL.

**Retention rule:** the 35-row arm must replicate a meaningful advantage in at least one predeclared identity endpoint—Pink Pepper recurrence, sport motion, transition, spatial separation, or takeover reduction—without a replicated loss elsewhere. “More complex,” higher modeled OAV, or a tiny preference difference is insufficient. If the 28-row arm is equal or better, the seven-row group is rejected and add-backs proceed one at a time or by functionally coherent pair.

## 11. Stage 6 — One-Musk Necessity

**Question:** does Romandolide provide an outward woody-fabric echo that the wood/amber matrix cannot provide by itself?

| Arm | Romandolide | Benzyl Benzoate add-back | Total |
|---|---:|---:|---:|
| M+ | 320 µL | 0 µL | 6,600 µL |
| M0 | 0 µL | 320 µL | 6,600 µL |

Retain Romandolide only if the coded arm has a clearer outward trail or fabric echo at 2-24 hours without laundry identity, blank musk drydown, or reduced Pink Pepper recurrence. No second musk is considered until this exact necessity test is complete.

## 12. Stage 7 — Whole-Product Benchmark Against the Rejected Predecessor

Compare the selected Pepper Current build with `SILVER_TRAVERSE_V1_3_1_EXACT_PINK_PEPPER_10pct_30mL_20pct_THEORY.md` only as a whole-product directional benchmark. Do not interpret it causally: concentration, chassis, row identities, and balances differ. If physical tests are ever authorized, either normalize finished concentration in a declared matched comparison or record concentration as an unresolved confound.

The replacement must win all three non-negotiable directional endpoints:

1. Pink Pepper is more clearly the first and recurring subject.
2. Sport/athletic motion is freely reported at 0-30 minutes.
3. Warm Parfum depth rises behind the sport surface without producing static heaviness.

Preference alone cannot override any of these three.

## 13. Decision Matrix

| Outcome | Decision |
|---|---|
| Pink Pepper not recognized versus vehicle control | stop; formula identity fails |
| Pink Pepper recognized but sport score fails at all DHM levels | stop; redesign motion engine before touching the base |
| sport passes but citrus leads | use lower citrus arm; do not raise Pink Pepper automatically |
| sport passes but drydown becomes anonymous amberwood | reduce rear pressure or strengthen exact subject recurrence; do not add more musk |
| warm module adds depth but causes static heaviness | test Ebanol/Amberwood components separately; retain only the non-static owner |
| mineral module adds motion but causes aquatic/muguet identity | compress M and add back one element at a time |
| 28 rows equal or beat 35 | promote compressed successor; reject decorative rows |
| Romandolide does not produce a replicated functional advantage | promote no-musk successor |
| identity and architecture pass but liking does not | revise hedonic pressure/release only; do not erase the lead nucleus |
| one preparation passes and the other fails | inconclusive; investigate preparation variance before redesign |

## 14. Required Record for Every Arm

- formula and authority hashes;
- bottle/lot/stock-basis ledger;
- operator, date/time, equipment, actual delivered amounts, and deviations;
- randomization seed or sealed code map;
- room conditions and substrate lot;
- raw free descriptions at every time window;
- completed structured ballots;
- missing observations and protocol deviations;
- unblinding timestamp;
- per-preparation results and combined result kept separate;
- explicit final state: `PASS`, `FAIL`, `INCONCLUSIVE`, `HOLD`, or `NOT TESTED`.

## 15. Current Readiness

This protocol is fully specified as a theory artifact, but physical readiness is **HOLD**. Pink Pepper stock-basis/composite-physics/safety reconciliation, Ambrofix carrier, formula-specific safety, batch scale, equipment, and explicit compounding authorization remain unresolved. No sensory or reference-similarity claim has been promoted.

**Final status:** THEORY PLAN COMPLETE / ALL PHYSICAL RESULTS NOT TESTED / NO COMPOUNDING OR PROCUREMENT AUTHORIZED
