"""Future Modules — Formulation Intelligence Pipeline Integration Layer.

**RULE 1: All perfume calculations must use ppm, ODT, and OAV.**

This package provides 12 specialized modules that encode the Formulation
Intelligence Database (May 2026) as composable, pipeline-integrable Python
modules. Each module follows the same conventions as the existing engine/
architecture: frozen dataclasses, stand-alone functions, comprehensive type
hints, and `from __future__ import annotations`.

Module summary:
  _shared_types            — Enums, constants, base dataclasses (shared vocabulary)
  construction_methodology — 10 quantified construction methods (A through J)
  balance_axes             — 8-axis balance evaluation
  family_hedonic_optimizer — Family-specific OAV targets, secret materials, pitfalls
  accord_library           — Quantified accord recipes (Grojsman, jasmine, chypre, etc.)
  synergy_matrix           — Synergy/antagonist pair database with quantitative factors
  character_shift_zones     — Hedonic dose-response zone database (indole, calone, etc.)
  chemical_compatibility    — Reactive pair detection and compatible stability checks
  performance_profiles     — VP, half-life, substantivity, sillage, climate correction
  dosing_tables            — µL dosing, stock preparation, potent material handling
  iteration_protocol       — Formula iteration timeline and Roudnitska stop criterion
  edge_cases               — Anosmia coverage, climate correction, solubility, ghost notes
  literature_references    — Tiered citation database (A through E)

Integration pattern:
  1. Import the relevant module
  2. Call its public functions with FormulaState or ingredient dicts
  3. Results are dataclasses or tuples — composable with the gate pipeline
"""

from __future__ import annotations

# Shared types (always imported — provides the vocabulary)
from ._shared_types import (
    # Enums
    ConcentrationBracket,
    DiffusionLayer,
    FragranceFamily,
    HedonicCategory,
    MarketSegment,
    MethodologyType,
    NoteTier,
    ReferenceTier,
    SolubilityRisk,
    TextureLayer,
    # Dataclasses
    AccordRecipe,
    AnosmiaData,
    AntagonistPair,
    BalanceReport,
    ChemicalReaction,
    CompatibilityReport,
    ConcentrationConversion,
    DosingEntry,
    FamilyFlaw,
    GhostNoteMaterial,
    IterationStage,
    MaterialShiftProfile,
    HedgeShiftZone,
    NaturalEOData,
    PerformanceData,
    PyramidRatio,
    Reference,
    SolubilityData,
    SynergyPair,
    # Constants
    ACTIVITY_COEFFICIENT_RANGES,
    BANGKOK_VP_RATIO,
    CROSS_FAMILY_COMPATIBILITY,
    DELTA_H_VAP_DEFAULT,
    FAMILY_FLAWS,
    FIXATIVE_LOADING,
    HEDONIC_TARGETS,
    HEDONIC_WEIGHTS,
    MACERATION_STAGES,
    MATERIAL_CLASS_DISTRIBUTION,
    MIN_OVERLAP_WINDOW_MINUTES,
    MIXTURE_SUPPRESSION_FACTOR,
    OAV_PERCEPTUAL_STATUS,
    OPTIMAL_ACCORD_COUNT,
    OPTIMAL_LOG_OAV_SD,
    PYRAMID_OAV_RATIOS,
    TEXTURE_RATIOS,
    TRANSITION_FAMILIES,
    # Utility functions
    accelerated_aging_time,
    clausius_clapeyron_vp_ratio,
    estimate_mixture_suppression,
    get_note_tier_from_vp,
    get_oav_perceptual_status,
)

# Construction methodology
from .construction_methodology import (
    ANCHOR_MATERIALS,
    COST_EFFICIENCY,
    IFRA_CAT4_LIMITS,
    METHODOLOGY_SPECS,
    MINIMUM_VIABLE_FORMULAS,
    MULTIFUNCTIONAL_MATERIALS,
    NATURAL_EXTENSIONS,
    TEXTURE_MATERIALS,
    AccordSpec,
    AnchorMaterial,
    CostEfficiencyData,
    FixativeStrategy,
    HedonicMaterialTarget,
    IFRAConstraint,
    MinimumViableFormula,
    NaturalExtension,
    PyramidBlueprint,
    apply_mixture_suppression,
    check_hedonic_distribution,
    check_ifra_compliance,
    compute_hedonic_objective,
    evaluate_pyramid_balance,
    evaporative_half_life_estimator,
    get_fixative_strategy,
    get_min_viable,
    get_oav_cost_efficiency,
    get_oav_sweet_spot,
    get_pyramid_blueprint,
    get_texture_blueprint,
    get_extension,
    get_texture_classification,
    materialize_accord_spec,
    recommend_accord_count,
    select_anchor,
)

# Balance axes
from .balance_axes import (
    MACERATION_RULES,
    MacerationRule,
    evaluate_all_balances,
    evaluate_cross_family_compatibility,
    evaluate_diffusion_layers,
    evaluate_hedonic_contrast,
    evaluate_maceration_risks,
    evaluate_material_class_distribution,
    evaluate_oav_contrast,
    evaluate_transparency_opacity,
    evaluate_volatility_balance,
    get_balance_overdose_strategy,
)

# Family hedonic optimizer
from .family_hedonic_optimizer import (
    AMBER_ORIENTAL_PROFILE,
    AROMATIC_FOUGERE_PROFILE,
    CHYPRE_PROFILE,
    CITRUS_HESPERIDIC,
    FAMILY_PROFILES,
    FLORAL_JASMINE_PROFILE,
    FLORAL_ROSE_PROFILE,
    GOURMAND_PROFILE,
    LEATHER_PROFILE,
    MARINE_AQUATIC_PROFILE,
    MUSK_PROFILE,
    PETRICHOR_PROFILE,
    TRANSPARENT_SKIN_PROFILE,
    WOODY_SANDALWOOD_PROFILE,
    FamilyHedonicProfile,
    FamilyMaterialTarget,
    check_family_cliffs,
    get_cliff_oav,
    get_family_profile,
    get_ifra_changes,
    get_oav_targets,
    list_family_performance_tips,
    list_family_pitfalls,
)

# Accord library
from .accord_library import (
    ALL_ACCORDS,
    ALDEHYDIC_FLORAL_ACCORD,
    CLASSIC_JASMINE_ACCORD,
    FOUGERE_BACKBONE,
    GREEN_ACCORD,
    GROJSMAN_ACCORD,
    LACTONIC_CREAM_ACCORD,
    MINERAL_PETRICHOR_ACCORD,
    MUGUET_ACCORD,
    PHOTOREALISTIC_ROSE_ACCORD,
    POST_IFRA_CHYPRE_BACKBONE,
    SYNTHETIC_OUD_ACCORD,
    TOBACCO_ACCORD,
    VIOLET_IRIS_ACCORD,
    get_accord,
    get_accord_character,
    get_accord_hedonic,
    list_accords,
    list_accords_by_family,
    materialize_accord,
    materialize_multi_accord_formula,
)

# Synergy matrix
from .synergy_matrix import (
    ANTAGONIST_PAIRS,
    SYNERGY_PAIRS,
    check_formula_conflicts,
    check_formula_synergies,
    get_all_antagonist_pairs,
    get_all_synergy_pairs,
    get_antagonist_pairs_material,
    get_synergy_factor,
    get_synergy_pairs_material,
)

# Character shift zones
from .character_shift_zones import (
    ALL_SHIFT_PROFILES,
    CALONE_PROFILE,
    COUMARIN_PROFILE,
    DAMASCENONE_PROFILE,
    ETHYL_MALTOL_PROFILE,
    GEOSMIN_PROFILE,
    IBQ_PROFILE,
    INDOLE_PROFILE,
    VANILLIN_PROFILE,
    check_zone_boundaries,
    get_current_zone,
    get_hill_parameters,
    get_shift_profile,
    get_zone_by_oav,
    hill_response,
    list_all_shift_profiles,
)

# Chemical compatibility
from .chemical_compatibility import (
    CHEMICAL_REACTIONS,
    check_formula_compatibility,
    classify_material_reactivity,
    detect_oxidation_risk,
    detect_schiff_base_risk,
    get_all_reactions,
    get_mitigation,
    get_reaction,
)

# Performance profiles
from .performance_profiles import (
    PERFORMANCE_DB,
    calculate_effective_half_life,
    calculate_hydrogen_bonding_matrix,
    calculate_logp_retardation,
    calculate_molecular_caging,
    calculate_vp_suppression,
    estimate_evaporation_timeline,
    estimate_tropical_performance_shift,
    get_bangkok_vp,
    get_half_life,
    get_logp,
    get_note_tier,
    get_performance,
    get_temperature_adjusted_vp,
    get_vp,
    list_all_performance,
    recommend_fixative_loading,
)

# Dosing tables
from .dosing_tables import (
    POTENT_MATERIALS,
    SAMPLE_DOSING_TABLE,
    SOLID_STOCK_RECIPES,
    VISCOUS_MATERIALS,
    PotentMaterialDilution,
    calculate_dose,
    calculate_ppm,
    calculate_target_percent,
    estimate_oav,
    get_all_sample_dosing,
    get_potent_dilution,
    get_sample_dosing,
    get_solid_stock,
    get_viscous_handling,
    list_potent,
    list_solids,
    list_viscous,
    prepare_stock_solution,
)

# Iteration protocol
from .iteration_protocol import (
    EVALUATION_DISTANCES,
    ITERATION_PROTOCOL,
    OVERDOSE_STRATEGIES,
    OverdoseStrategy,
    accelerated_aging_equivalent,
    evaluate_stage_compliance,
    format_iteration_status,
    get_all_stages,
    get_evaluation_distances,
    get_maceration_milestone,
    get_next_stage,
    get_overdose_strategy,
    get_stage_by_day,
    get_stage_by_name,
    roudnitska_test,
)

# Edge cases
from .edge_cases import (
    ANOSMIA_DATABASE,
    COLD_SHIPPING_RISKS,
    CONCENTRATION_CONVERSIONS,
    GHOST_NOTE_MATERIALS,
    MUSK_CLASS_COVERAGE,
    NATURAL_EO_DATA,
    adjust_for_concentration,
    calculate_eo_oav,
    candle_compatibility,
    check_musk_class_coverage,
    check_solubility_risk,
    clausius_clapeyron_factor,
    estimate_anosmia_coverage,
    estimate_evaporation_acceleration,
    get_anosmia,
    get_concentration_conversion,
    get_eo_character_constituent,
    get_ghost_note,
    humidity_effects,
    is_ghost_note_material,
    thai_market_check,
    tropical_base_loading_correction,
)

# Literature references
from .literature_references import (
    ALL_REFERENCES,
    TIER_A,
    TIER_B,
    TIER_C,
    TIER_D,
    TIER_E,
    TOPIC_REFERENCES,
    cite,
    get_all_references,
    get_reference,
    get_references_by_tier,
    get_references_by_topic,
    get_tier_counts,
    get_topic_keys,
)

# Iconic formula archaeology
from .iconic_formulas import (
    ALL_SKELETONS,
    AVENTUS_SKELETON,
    BLACK_ORCHID_SKELETON,
    CHANEL_NO5_SKELETON,
    FIVE_LUXURY_PRINCIPLES as ICONIC_FIVE_PRINCIPLES,
    INTERLUDE_SKELETON,
    LAYTON_SKELETON,
    SAUVAGE_SKELETON,
    AldehydeQuartet,
    FormulaSkeleton,
    find_formulas_by_family,
    get_aldehyde_quartet,
    get_anosmia_warnings,
    get_construction_methods,
    get_skeleton,
    get_three_pillar_platforms,
    get_tropical_notes,
    list_skeletons,
)

# Advanced musk intelligence
from .advanced_musk_intelligence import (
    CASHMERAN,
    HELVETOLIDE,
    INFRASTRUCTURE_MATERIALS,
    MUSK_CLASSES,
    NORLIMBANOL,
    ROMANDOLIDE,
    VERTOFIX_COEUR,
    WOODY_INFRASTRUCTURE_TRIO,
    CashmeranProfile,
    HelvetolideProfile,
    MuskClassProfile,
    NorlimbanolProfile,
    RomandolideProfile,
    VertofixCoeurProfile,
    WoodyInfrastructureTrio,
    get_all_musk_classes,
    get_cashmeran_profile,
    get_east_asian_caution_musks,
    get_helvetolide_profile,
    get_infrastructure_materials,
    get_musk_class_profile,
    get_norlimbanol_profile,
    get_romandolide_profile,
    get_universal_musks,
    get_vertofix_coeur_profile,
    get_woody_infrastructure_trio,
    recommend_thai_musk_platform,
)

# Skin chemistry
from .skin_chemistry import (
    HORMONAL_CONTEXTS,
    PH_EFFECTS,
    SKIN_PREPARATION_GUIDE,
    SKIN_TYPE_PROFILES,
    THAI_SKIN,
    HormonalContext,
    PhEffectRule,
    SkinTypeProfile,
    ThaiSkinProfile,
    estimate_sebum_depot_factor,
    formulate_for_skin_type,
    get_hormonal_context,
    get_ph_effect,
    get_skin_profile,
    get_thai_skin_profile,
    recommend_logp_strategy,
    thai_base_material_score,
)

# Somatosensory effects
from .somatosensory import (
    SOMATOSENSORY_DESIGN_PATTERNS,
    SOMATOSENSORY_MATERIALS,
    TRP_CHANNELS,
    SomatosensoryMaterial,
    TrpChannel,
    classify_somatosensory_effect,
    get_all_design_patterns,
    get_all_somatosensory_materials,
    get_all_trp_channels,
    get_design_pattern,
    get_materials_by_channel,
    get_somatosensory_material,
    get_trp_channel,
    recommend_somatosensory_for_context,
)

# Evaluation protocol
from .evaluation_protocol import (
    APPLICATION_RULES,
    BLOTTER_SCHEDULE,
    DOWNGRADE_INDICATORS,
    FATIGUE_RULES,
    FIVE_DISTANCE_GRID,
    SKIN_APPLICATION_POINTS,
    ApplicationRule,
    BlotterEvaluationPoint,
    DistanceZone,
    FatigueRule,
    SkinApplicationPoint,
    evaluate_sephora_house_level,
    format_blotter_timeline,
    get_application_rules,
    get_blotter_schedule,
    get_downgrade_indicators,
    get_fatigue_rules,
    get_five_distance_grid,
    get_skin_application_points,
    get_zone_by_distance,
)

# Niche construction
from .niche_construction import (
    CONSTRUCTION_CONTINUUM,
    DIFFUSION_PLATFORMS,
    DRAMATIC_ARC_STRUCTURE,
    FIVE_LUXURY_PRINCIPLES,
    MOLECULE_FORWARD_ANCHORS,
    ConstructionStyle,
    DiffusionPlatform,
    DramaticAct,
    MoleculeForwardBlueprint,
    build_concept_strip,
    design_dramatic_arc,
    get_act_materials,
    get_all_construction_styles,
    get_all_diffusion_platforms,
    get_all_molecule_forward_anchors,
    get_construction_style,
    get_diffusion_platform,
    get_dramatic_arc_structure,
    get_five_luxury_principles,
    get_molecule_forward_blueprint,
)

# Brief translation
from .brief_translation import (
    BRIEF_TRANSLATIONS,
    MATERIAL_EMOTION_MAP,
    BriefTranslation,
    build_concept_strip as brief_build_concept_strip,
    find_materials_by_emotion,
    generate_constraints,
    get_all_brief_translations,
    get_emotions_for_material,
    translate_brief,
    translate_brief_element,
)

# Captive materials
from .captive_materials import (
    ADDITIONAL_MATERIALS,
    ALL_CAPTIVES,
    COST_TIERS,
    FIRMENICH_CAPTIVES,
    GIVAUDAN_CAPTIVES,
    IFF_CAPTIVES,
    INDEPENDENT_STRATEGIES,
    SYMRISE_CAPTIVES,
    AdditionalMaterial,
    CaptiveMaterial,
    CostTier,
    get_additional_material,
    get_all_additional_materials,
    get_all_cost_tiers,
    get_captives_by_house,
    get_cost_tier,
    get_independent_strategies,
    get_now_available_captives,
    get_still_captive,
    get_substitute,
    recommend_thai_captive_alternatives,
)

# Blending protocol
from .blending_protocol import (
    MIXING_SEQUENCE,
    POST_MIXING_PROTOCOL,
    SCHIFF_BASE_PREVENTION,
    SOLVENT_MATRIX,
    TEMPERATURE_RULES,
    MixingStep,
    SchiffBasePrevention,
    SolventMatrixGuide,
    TemperatureRule,
    check_aldehyde_amine_conflict,
    get_mixing_sequence,
    get_mixing_step,
    get_post_mixing_protocol,
    get_schiff_base_prevention,
    get_solvent_matrix_guide,
    get_temperature_rules,
    recommend_solvent_mix,
)


__all__ = [
    # --- _shared_types — Enums ---
    "ConcentrationBracket",
    "DiffusionLayer",
    "FragranceFamily",
    "HedonicCategory",
    "MarketSegment",
    "MethodologyType",
    "NoteTier",
    "ReferenceTier",
    "SolubilityRisk",
    "TextureLayer",
    # --- _shared_types — Dataclasses ---
    "AccordRecipe",
    "AnosmiaData",
    "AntagonistPair",
    "BalanceReport",
    "ChemicalReaction",
    "CompatibilityReport",
    "ConcentrationConversion",
    "DosingEntry",
    "FamilyFlaw",
    "GhostNoteMaterial",
    "IterationStage",
    "MaterialShiftProfile",
    "HedgeShiftZone",
    "NaturalEOData",
    "PerformanceData",
    "PyramidRatio",
    "Reference",
    "SolubilityData",
    "SynergyPair",
    # --- _shared_types — Constants ---
    "ACTIVITY_COEFFICIENT_RANGES",
    "BANGKOK_VP_RATIO",
    "CROSS_FAMILY_COMPATIBILITY",
    "DELTA_H_VAP_DEFAULT",
    "FAMILY_FLAWS",
    "FIXATIVE_LOADING",
    "HEDONIC_TARGETS",
    "HEDONIC_WEIGHTS",
    "MACERATION_STAGES",
    "MATERIAL_CLASS_DISTRIBUTION",
    "MIXTURE_SUPPRESSION_FACTOR",
    "OAV_PERCEPTUAL_STATUS",
    "OPTIMAL_LOG_OAV_SD",
    "PYRAMID_OAV_RATIOS",
    "TEXTURE_RATIOS",
    "TRANSITION_FAMILIES",
    # --- _shared_types — Functions ---
    "accelerated_aging_time",
    "clausius_clapeyron_vp_ratio",
    "estimate_mixture_suppression",
    "get_note_tier_from_vp",
    "get_oav_perceptual_status",
    # --- construction_methodology ---
    "ANCHOR_MATERIALS",
    "COST_EFFICIENCY",
    "IFRA_CAT4_LIMITS",
    "METHODOLOGY_SPECS",
    "MINIMUM_VIABLE_FORMULAS",
    "MULTIFUNCTIONAL_MATERIALS",
    "NATURAL_EXTENSIONS",
    "TEXTURE_MATERIALS",
    "AccordSpec",
    "AnchorMaterial",
    "CostEfficiencyData",
    "FixativeStrategy",
    "HedonicMaterialTarget",
    "IFRAConstraint",
    "MinimumViableFormula",
    "NaturalExtension",
    "PyramidBlueprint",
    "apply_mixture_suppression",
    "check_hedonic_distribution",
    "check_ifra_compliance",
    "compute_hedonic_objective",
    "evaluate_pyramid_balance",
    "evaporative_half_life_estimator",
    "get_extension",
    "get_fixative_strategy",
    "get_min_viable",
    "get_oav_cost_efficiency",
    "get_oav_sweet_spot",
    "get_pyramid_blueprint",
    "get_texture_blueprint",
    "get_texture_classification",
    "materialize_accord_spec",
    "recommend_accord_count",
    "select_anchor",
    # --- balance_axes ---
    "MACERATION_RULES",
    "MacerationRule",
    "evaluate_all_balances",
    "evaluate_cross_family_compatibility",
    "evaluate_diffusion_layers",
    "evaluate_hedonic_contrast",
    "evaluate_maceration_risks",
    "evaluate_material_class_distribution",
    "evaluate_oav_contrast",
    "evaluate_transparency_opacity",
    "evaluate_volatility_balance",
    "get_balance_overdose_strategy",
    # --- family_hedonic_optimizer ---
    "AMBER_ORIENTAL_PROFILE",
    "AROMATIC_FOUGERE_PROFILE",
    "CHYPRE_PROFILE",
    "CITRUS_HESPERIDIC",
    "FAMILY_PROFILES",
    "FLORAL_JASMINE_PROFILE",
    "FLORAL_ROSE_PROFILE",
    "GOURMAND_PROFILE",
    "LEATHER_PROFILE",
    "MARINE_AQUATIC_PROFILE",
    "MUSK_PROFILE",
    "PETRICHOR_PROFILE",
    "TRANSPARENT_SKIN_PROFILE",
    "WOODY_SANDALWOOD_PROFILE",
    "FamilyHedonicProfile",
    "FamilyMaterialTarget",
    "check_family_cliffs",
    "get_cliff_oav",
    "get_family_profile",
    "get_ifra_changes",
    "get_oav_targets",
    "list_family_performance_tips",
    "list_family_pitfalls",
    # --- accord_library ---
    "ALL_ACCORDS",
    "ALDEHYDIC_FLORAL_ACCORD",
    "CLASSIC_JASMINE_ACCORD",
    "FOUGERE_BACKBONE",
    "GREEN_ACCORD",
    "GROJSMAN_ACCORD",
    "LACTONIC_CREAM_ACCORD",
    "MINERAL_PETRICHOR_ACCORD",
    "MUGUET_ACCORD",
    "PHOTOREALISTIC_ROSE_ACCORD",
    "POST_IFRA_CHYPRE_BACKBONE",
    "SYNTHETIC_OUD_ACCORD",
    "TOBACCO_ACCORD",
    "VIOLET_IRIS_ACCORD",
    "get_accord",
    "get_accord_character",
    "get_accord_hedonic",
    "list_accords",
    "list_accords_by_family",
    "materialize_accord",
    "materialize_multi_accord_formula",
    # --- synergy_matrix ---
    "ANTAGONIST_PAIRS",
    "SYNERGY_PAIRS",
    "check_formula_conflicts",
    "check_formula_synergies",
    "get_all_antagonist_pairs",
    "get_all_synergy_pairs",
    "get_antagonist_pairs_material",
    "get_synergy_factor",
    "get_synergy_pairs_material",
    # --- character_shift_zones ---
    "ALL_SHIFT_PROFILES",
    "CALONE_PROFILE",
    "COUMARIN_PROFILE",
    "DAMASCENONE_PROFILE",
    "ETHYL_MALTOL_PROFILE",
    "GEOSMIN_PROFILE",
    "IBQ_PROFILE",
    "INDOLE_PROFILE",
    "VANILLIN_PROFILE",
    "check_zone_boundaries",
    "get_current_zone",
    "get_hill_parameters",
    "get_shift_profile",
    "get_zone_by_oav",
    "hill_response",
    "list_all_shift_profiles",
    # --- chemical_compatibility ---
    "CHEMICAL_REACTIONS",
    "check_formula_compatibility",
    "classify_material_reactivity",
    "detect_oxidation_risk",
    "detect_schiff_base_risk",
    "get_all_reactions",
    "get_mitigation",
    "get_reaction",
    # --- performance_profiles ---
    "PERFORMANCE_DB",
    "calculate_effective_half_life",
    "calculate_hydrogen_bonding_matrix",
    "calculate_logp_retardation",
    "calculate_molecular_caging",
    "calculate_vp_suppression",
    "estimate_evaporation_timeline",
    "estimate_tropical_performance_shift",
    "get_bangkok_vp",
    "get_half_life",
    "get_logp",
    "get_note_tier",
    "get_performance",
    "get_temperature_adjusted_vp",
    "get_vp",
    "list_all_performance",
    "recommend_fixative_loading",
    # --- dosing_tables ---
    "POTENT_MATERIALS",
    "SAMPLE_DOSING_TABLE",
    "SOLID_STOCK_RECIPES",
    "VISCOUS_MATERIALS",
    "PotentMaterialDilution",
    "calculate_dose",
    "calculate_ppm",
    "calculate_target_percent",
    "estimate_oav",
    "get_all_sample_dosing",
    "get_potent_dilution",
    "get_sample_dosing",
    "get_solid_stock",
    "get_viscous_handling",
    "list_potent",
    "list_solids",
    "list_viscous",
    "prepare_stock_solution",
    # --- iteration_protocol ---
    "EVALUATION_DISTANCES",
    "ITERATION_PROTOCOL",
    "OVERDOSE_STRATEGIES",
    "OverdoseStrategy",
    "accelerated_aging_equivalent",
    "evaluate_stage_compliance",
    "format_iteration_status",
    "get_all_stages",
    "get_evaluation_distances",
    "get_maceration_milestone",
    "get_next_stage",
    "get_overdose_strategy",
    "get_stage_by_day",
    "get_stage_by_name",
    "roudnitska_test",
    # --- edge_cases ---
    "ANOSMIA_DATABASE",
    "COLD_SHIPPING_RISKS",
    "CONCENTRATION_CONVERSIONS",
    "GHOST_NOTE_MATERIALS",
    "MUSK_CLASS_COVERAGE",
    "NATURAL_EO_DATA",
    "adjust_for_concentration",
    "calculate_eo_oav",
    "candle_compatibility",
    "check_musk_class_coverage",
    "check_solubility_risk",
    "clausius_clapeyron_factor",
    "estimate_anosmia_coverage",
    "estimate_evaporation_acceleration",
    "get_anosmia",
    "get_concentration_conversion",
    "get_eo_character_constituent",
    "get_ghost_note",
    "humidity_effects",
    "is_ghost_note_material",
    "thai_market_check",
    "tropical_base_loading_correction",
    # --- literature_references ---
    "ALL_REFERENCES",
    "TIER_A",
    "TIER_B",
    "TIER_C",
    "TIER_D",
    "TIER_E",
    "TOPIC_REFERENCES",
    "cite",
    "get_all_references",
    "get_reference",
    "get_references_by_tier",
    "get_references_by_topic",
    "get_tier_counts",
    "get_topic_keys",
    # --- iconic_formulas ---
    "ALL_SKELETONS",
    "AVENTUS_SKELETON",
    "BLACK_ORCHID_SKELETON",
    "CHANEL_NO5_SKELETON",
    "INTERLUDE_SKELETON",
    "LAYTON_SKELETON",
    "SAUVAGE_SKELETON",
    "ICONIC_FIVE_PRINCIPLES",
    "AldehydeQuartet",
    "FormulaSkeleton",
    "find_formulas_by_family",
    "get_aldehyde_quartet",
    "get_anosmia_warnings",
    "get_construction_methods",
    "get_skeleton",
    "get_three_pillar_platforms",
    "get_tropical_notes",
    "list_skeletons",
    # --- advanced_musk_intelligence ---
    "CASHMERAN",
    "HELVETOLIDE",
    "INFRASTRUCTURE_MATERIALS",
    "MUSK_CLASSES",
    "NORLIMBANOL",
    "ROMANDOLIDE",
    "VERTOFIX_COEUR",
    "WOODY_INFRASTRUCTURE_TRIO",
    "CashmeranProfile",
    "HelvetolideProfile",
    "MuskClassProfile",
    "NorlimbanolProfile",
    "RomandolideProfile",
    "VertofixCoeurProfile",
    "WoodyInfrastructureTrio",
    "get_all_musk_classes",
    "get_cashmeran_profile",
    "get_east_asian_caution_musks",
    "get_helvetolide_profile",
    "get_infrastructure_materials",
    "get_musk_class_profile",
    "get_norlimbanol_profile",
    "get_romandolide_profile",
    "get_universal_musks",
    "get_vertofix_coeur_profile",
    "get_woody_infrastructure_trio",
    "recommend_thai_musk_platform",
    # --- skin_chemistry ---
    "HORMONAL_CONTEXTS",
    "PH_EFFECTS",
    "SKIN_PREPARATION_GUIDE",
    "SKIN_TYPE_PROFILES",
    "THAI_SKIN",
    "HormonalContext",
    "PhEffectRule",
    "SkinTypeProfile",
    "ThaiSkinProfile",
    "estimate_sebum_depot_factor",
    "formulate_for_skin_type",
    "get_hormonal_context",
    "get_ph_effect",
    "get_skin_profile",
    "get_thai_skin_profile",
    "recommend_logp_strategy",
    "thai_base_material_score",
    # --- somatosensory ---
    "SOMATOSENSORY_DESIGN_PATTERNS",
    "SOMATOSENSORY_MATERIALS",
    "TRP_CHANNELS",
    "SomatosensoryMaterial",
    "TrpChannel",
    "classify_somatosensory_effect",
    "get_all_design_patterns",
    "get_all_somatosensory_materials",
    "get_all_trp_channels",
    "get_design_pattern",
    "get_materials_by_channel",
    "get_somatosensory_material",
    "get_trp_channel",
    "recommend_somatosensory_for_context",
    # --- evaluation_protocol ---
    "APPLICATION_RULES",
    "BLOTTER_SCHEDULE",
    "DOWNGRADE_INDICATORS",
    "FATIGUE_RULES",
    "FIVE_DISTANCE_GRID",
    "SKIN_APPLICATION_POINTS",
    "ApplicationRule",
    "BlotterEvaluationPoint",
    "DistanceZone",
    "FatigueRule",
    "SkinApplicationPoint",
    "evaluate_sephora_house_level",
    "format_blotter_timeline",
    "get_application_rules",
    "get_blotter_schedule",
    "get_downgrade_indicators",
    "get_fatigue_rules",
    "get_five_distance_grid",
    "get_skin_application_points",
    "get_zone_by_distance",
    # --- niche_construction ---
    "CONSTRUCTION_CONTINUUM",
    "DIFFUSION_PLATFORMS",
    "DRAMATIC_ARC_STRUCTURE",
    "FIVE_LUXURY_PRINCIPLES",
    "MOLECULE_FORWARD_ANCHORS",
    "ConstructionStyle",
    "DiffusionPlatform",
    "DramaticAct",
    "MoleculeForwardBlueprint",
    "build_concept_strip",
    "design_dramatic_arc",
    "get_act_materials",
    "get_all_construction_styles",
    "get_all_diffusion_platforms",
    "get_all_molecule_forward_anchors",
    "get_construction_style",
    "get_diffusion_platform",
    "get_dramatic_arc_structure",
    "get_five_luxury_principles",
    "get_molecule_forward_blueprint",
    # --- brief_translation ---
    "BRIEF_TRANSLATIONS",
    "MATERIAL_EMOTION_MAP",
    "BriefTranslation",
    "brief_build_concept_strip",
    "find_materials_by_emotion",
    "generate_constraints",
    "get_all_brief_translations",
    "get_emotions_for_material",
    "translate_brief",
    "translate_brief_element",
    # --- captive_materials ---
    "ADDITIONAL_MATERIALS",
    "ALL_CAPTIVES",
    "COST_TIERS",
    "FIRMENICH_CAPTIVES",
    "GIVAUDAN_CAPTIVES",
    "IFF_CAPTIVES",
    "INDEPENDENT_STRATEGIES",
    "SYMRISE_CAPTIVES",
    "AdditionalMaterial",
    "CaptiveMaterial",
    "CostTier",
    "get_additional_material",
    "get_all_additional_materials",
    "get_all_cost_tiers",
    "get_captives_by_house",
    "get_cost_tier",
    "get_independent_strategies",
    "get_now_available_captives",
    "get_still_captive",
    "get_substitute",
    "recommend_thai_captive_alternatives",
    # --- blending_protocol ---
    "MIXING_SEQUENCE",
    "POST_MIXING_PROTOCOL",
    "SCHIFF_BASE_PREVENTION",
    "SOLVENT_MATRIX",
    "TEMPERATURE_RULES",
    "MixingStep",
    "SchiffBasePrevention",
    "SolventMatrixGuide",
    "TemperatureRule",
    "check_aldehyde_amine_conflict",
    "get_mixing_sequence",
    "get_mixing_step",
    "get_post_mixing_protocol",
    "get_schiff_base_prevention",
    "get_solvent_matrix_guide",
    "get_temperature_rules",
    "recommend_solvent_mix",
]
