"""Build C evidence and physical-context contracts.

This package represents condition-aware thermophysical evidence and versioned
matrix/application context. It does not evaluate thermodynamic equations.
It does not authorize scientific release.
"""

from engine.physics.matrix_environment import (
    ApplicationEnvironment,
    ApplicationEnvironmentKind,
    CompositionCompleteness,
    DeclaredQuantity,
    EnvironmentField,
    MatrixAwareModelRequest,
    MatrixComponent,
    MatrixComponentRole,
    MatrixComposition,
    MatrixEnvironmentContractError,
    MatrixMissingField,
    MatrixQuantityBasis,
    MatrixStage,
)
from engine.physics.properties import (
    CanonicalScope,
    ClaimGrade,
    PropertyConditions,
    PropertyDatum,
    PropertyIdentity,
    PropertyValueKind,
    SelectionStatus,
    SourceReference,
    ThermophysicalContractError,
    ThermophysicalProperty,
    UncertaintyDescriptor,
    UncertaintyKind,
)
from engine.physics.selection import (
    AuthorityState,
    InterpolationState,
    MissingDataReason,
    PropertyRequest,
    PropertySelectionResult,
    PropertySelectionService,
    SelectedPropertyAssertion,
    SelectionKind,
    selected_assertion_from_b2_reconstruction,
)
from engine.physics.vapor_pressure import (
    ExtrapolationPolicy,
    TemperatureRange,
    VaporPressureCoefficient,
    VaporPressureEquationType,
    VaporPressurePoint,
    VaporPressureRepresentation,
)

__all__ = [
    "ApplicationEnvironment",
    "ApplicationEnvironmentKind",
    "AuthorityState",
    "CanonicalScope",
    "ClaimGrade",
    "CompositionCompleteness",
    "DeclaredQuantity",
    "EnvironmentField",
    "ExtrapolationPolicy",
    "InterpolationState",
    "MissingDataReason",
    "MatrixAwareModelRequest",
    "MatrixComponent",
    "MatrixComponentRole",
    "MatrixComposition",
    "MatrixEnvironmentContractError",
    "MatrixMissingField",
    "MatrixQuantityBasis",
    "MatrixStage",
    "PropertyConditions",
    "PropertyDatum",
    "PropertyIdentity",
    "PropertyRequest",
    "PropertySelectionResult",
    "PropertySelectionService",
    "PropertyValueKind",
    "SelectedPropertyAssertion",
    "SelectionKind",
    "SelectionStatus",
    "SourceReference",
    "TemperatureRange",
    "ThermophysicalContractError",
    "ThermophysicalProperty",
    "UncertaintyDescriptor",
    "UncertaintyKind",
    "VaporPressureCoefficient",
    "VaporPressureEquationType",
    "VaporPressurePoint",
    "VaporPressureRepresentation",
    "selected_assertion_from_b2_reconstruction",
]
